module Coordinator::Processes::BuildProgress
  class SourceBuilder
    def initialize: (event_store: Coordinator::Write::_EventStore, ?contract: Coordinator::Processes::Contracts::BuildProgressSourceEvent, ?schema_registry: Coordinator::Write::EventSchemaRegistry, ?stream_factory: Coordinator::Write::StreamFactory, ?release_history_loader: Coordinator::Write::ReleaseSets::HistoryLoader) -> void
    def call: (PgEventstore::Event event) -> SourceV1
  end
end
