module Coordinator
  module Write
    module Commands
      class AbandonHistoryMigration < Shared::Value
        attr_reader command_id: String
        attr_reader actor: Actor
        attr_reader migration_id: String
        attr_reader reason: String
      end
    end
  end
end
