module Coordinator
  module Write
    module Commands
      class AdvanceHistoryMigrationApplication < Shared::Value
        def command_id: () -> String
        def actor: () -> Actor
        def migration_id: () -> String
        def page_id: () -> String
        def dependency_wave: () -> Integer
        def next_dependency_wave: () -> Integer
        def next_from_position: () -> Integer
      end
    end
  end
end
