module Coordinator
  module Write
    module Commands
      class AdvanceHistoryMigration < Shared::Value
        attr_reader command_id: String
        attr_reader actor: Actor
        attr_reader migration_id: String
        attr_reader page_id: String
        attr_reader next_from_position: Integer
      end
    end
  end
end
