module Coordinator
  module Write
    module Commands
      class ApplyHistoryMigrationPage < Shared::Value
        attr_reader command_id: String
        attr_reader actor: Actor
        attr_reader page_id: String
      end
    end
  end
end
