module Coordinator
  module Write
    module Commands
      class CaptureDevelopmentArtifact < Shared::Value
        def command_id: () -> String
        def actor: () -> Actor
        def artifact: () -> DevelopmentArtifacts::ArtifactV2
        def observation: () -> DevelopmentArtifacts::ArtifactObservationV1
      end
    end
  end
end
