module Coordinator
  module Write
    module Commands
      class CompleteHistoryMigrationPlan < Shared::Value
        def command_id: () -> String
        def actor: () -> Actor
        def migration_id: () -> String
      end
    end
  end
end
