module Coordinator
  module Write
    module Commands
      class CreateHistoryMigrationPage < Shared::Value
        attr_reader command_id: String
        attr_reader actor: Actor
        attr_reader migration_id: String
        attr_reader page_id: String
        attr_reader from_position: Integer
        attr_reader to_position: Integer
        attr_reader source_event_count: Integer
      end
    end
  end
end
