module Coordinator
  module Write
    module Commands
      class CreateHistoryMigrationTargetStreamPlan < Shared::Value
        def command_id: () -> String
        def actor: () -> Actor
        def event_id: () -> String
        def migration_id: () -> String
        def plan_id: () -> String
        def target_stream_context: () -> String
        def target_stream_name: () -> String
        def target_stream_id: () -> String
      end
    end
  end
end
