module Coordinator
  module Write
    module Commands
      class CreateChangeSet < Shared::Value
        def command_id: () -> String
        def actor: () -> Actor
        def change_set_id: () -> String
        def goal: () -> String
        def acceptance_criteria: () -> Array[String]
      end
    end
  end
end
