module Coordinator
  module Write
    module Commands
      class RecordCoordinationTaskOutcome < Shared::Value
        def task_id: () -> String
        def outcome: () -> Tasks::OutcomeV3::value
      end
    end
  end
end
