module Coordinator
  module Write
    module Commands
      class ReleaseLeaseSet < Shared::Value
        def command_id: () -> String
        def actor: () -> Actor
        def change_set_id: () -> String
        def work_item_id: () -> String
        def attempt_id: () -> String
        def lease_set_id: () -> String
        def leases: () -> Array[LeaseReleaseReferenceV2]
      end
    end
  end
end
