module Coordinator
  module Write
    module Commands
      class StartHistoryMigration < Shared::Value
        def command_id: () -> String
        def actor: () -> Actor
        def migration_id: () -> String
        def source_config_name: () -> String
        def target_config_name: () -> String
        def source_upper_position: () -> Integer?
        def page_size: () -> Integer
        def source_after_position: () -> Integer?
        def source_command_ids: () -> Array[String]
      end
    end
  end
end
