module Coordinator
  module Write
    module Commands
      class UpdateDevelopmentArtifact < Shared::Value
        def command_id: () -> String
        def actor: () -> Actor
        def artifact_id: () -> String
        def expected_revision: () -> Integer
        def changes: () -> DevelopmentArtifacts::UpdateChangesV1
      end
    end
  end
end
