module Coordinator
  module Write
    module Commands
      class WithdrawWorkIntentionSet < Shared::Value
        def command_id: () -> String
        def actor: () -> Actor
        def change_set_id: () -> String
        def work_item_id: () -> String
        def attempt_id: () -> String
        def intention_set_id: () -> String
        def intentions: () -> Array[WorkIntentionFencedReferenceV1]
      end
    end
  end
end
