module Coordinator
  module Write
    module Decisions
      class DecisionSlotBuilder
        EXCLUSIVE_STRATEGIES: Array[String]

        def initialize: (?id_generator: Shared::IdGenerator, ?marker_component_builder: Shared::CanonicalMarkerComponentBuilder, ?compound_marker_builder: Shared::CompoundMarkerBuilder) -> void
        def call: (DecisionDefinitionV1 definition) -> DecisionSlotV1?
      end
    end
  end
end
