module Coordinator
  module Write
    module HistoryMigrations
      class ChangeSetV1Transformer
        def initialize: (
          stream_identity_allocator: StreamIdentityAllocator,
          entity_reference_resolver: LegacyEntityReferenceResolver
        ) -> void

        def call: (
          migration_id: String,
          source_config_name: String,
          source_upper_position: Integer,
          source_event: PgEventstore::Event,
          source_payload: Events::ChangeSetCreatedV1 | Events::ChangeSetAcceptanceCriteriaDefinedV1 | Events::ChangeSetActivatedV1 | Events::ChangeSetCompletedV1
        ) -> Dry::Monads::Result
      end
    end
  end
end
