module Coordinator
  module Write
    module HistoryMigrations
      class CommandCompletedV1Transformer
        def initialize: (
          stream_identity_allocator: StreamIdentityAllocator,
          submission_resolver: LegacyCoordinationTaskSubmissionResolver,
          ?request_id_mapper: LegacyRequestIdMapper,
          ?request_marker: CommandLifecycle::RequestMarker
        ) -> void

        def call: (
          migration_id: String,
          source_config_name: String,
          source_upper_position: Integer?,
          source_event: PgEventstore::Event,
          source_payload: LegacyEvents::CommandCompletedV1
        ) -> Dry::Monads::Result
      end
    end
  end
end
