module Coordinator
  module Write
    module HistoryMigrations
      class CommandInputRebinder
        def initialize: (
          ?target_command_builder: Tasks::TargetCommandBuilder,
          ?input_digest: CommandInputDigest
        ) -> void
        def call: (document: CommandInputDocuments::value, command_id: String) -> MigratedCommandInputV1
      end
    end
  end
end
