module Coordinator
  module Write
    module HistoryMigrations
      class CorrelationAllocationV1 < Shared::Value
        def target_correlation_id: () -> String
        def allocation_event: () -> PgEventstore::Event
        def outcome: () -> String
      end
    end
  end
end
