module Coordinator
  module Write
    module HistoryMigrations
      class DecisionHeadReferenceResolver
        TARGETS: Hash[String, [String, String]]

        def initialize: (target_event_reference_resolver: LegacyTargetEventReferenceResolver) -> void

        def call: (
          migration_id: String,
          source_config_name: String,
          source_upper_position: Integer,
          source_event: PgEventstore::Event,
          head: Decisions::DecisionHeadV1
        ) -> Dry::Monads::Result
      end
    end
  end
end
