module Coordinator
  module Write
    module HistoryMigrations
      class DevelopmentArtifactSourceStateV1 < Shared::Value
        def legacy_artifact_id: () -> String
        def scope: () -> String
        def title: () -> String
        def kind: () -> String
        def source: () -> DevelopmentArtifacts::SourceV1
        def content: () -> (Content::TextV1 | Content::BinaryV1)
        def created_origin: () -> DevelopmentArtifactPropertyOriginV1
        def scope_origin: () -> DevelopmentArtifactPropertyOriginV1
        def title_origin: () -> DevelopmentArtifactPropertyOriginV1
        def kind_origin: () -> DevelopmentArtifactPropertyOriginV1
        def source_origin: () -> DevelopmentArtifactPropertyOriginV1
        def content_origin: () -> DevelopmentArtifactPropertyOriginV1
        def labels: () -> Array[DevelopmentArtifactLabelStateV1]
      end
    end
  end
end
