module Coordinator
  module Write
    module HistoryMigrations
      class DevelopmentArtifactLabelStateV1 < Shared::Value
        def label: () -> String
        def origin: () -> DevelopmentArtifactPropertyOriginV1
      end
    end
  end
end
