module Coordinator
  module Write
    module HistoryMigrations
      class DevelopmentArtifactMigrationContextV1 < Shared::Value
        def artifact_stream: () -> StreamReference
        def artifact_id: () -> String
        def observation_stream: () -> StreamReference?
        def observation_id: () -> String?
        def state: () -> DevelopmentArtifactSourceStateV1
      end
    end
  end
end
