module Coordinator
  module Write
    module HistoryMigrations
      class DevelopmentArtifactStateTransition
        def call: (
          state: DevelopmentArtifactSourceStateV1,
          source: LegacyEvents::DevelopmentArtifactObservedV1 |
                  LegacyEvents::DevelopmentArtifactClassificationCorrectedV1,
          source_event: PgEventstore::Event
        ) -> DevelopmentArtifactTransitionV1
      end
    end
  end
end
