module Coordinator
  module Write
    module HistoryMigrations
      class GuidanceMessageIdentityV1 < Shared::Value
        type source_message = Events::UserUtteranceRecordedV1 | Events::UserUtteranceForwardedByAgentV1

        def source_message: () -> source_message
        def source_event: () -> PgEventstore::Event
        def target_message_id: () -> String
      end
    end
  end
end
