module Coordinator
  module Write
    module HistoryMigrations
      class InterpretationContextV1 < Shared::Value
        def source_proposal: () -> Events::DecisionInterpretationProposedV1
        def source_proposal_event: () -> PgEventstore::Event
        def target_stream: () -> StreamReference
        def interpretation_id: () -> String
        def source_message_id: () -> String
        def source_text: () -> String
      end
    end
  end
end
