module Coordinator
  module Write
    module HistoryMigrations
      class LegacyMarkedEventLocator
        def initialize: (event_store: EventStore) -> void

        def call: (
          source_event: PgEventstore::Event,
          source_upper_position: Integer,
          stream_context: String,
          stream_name: String,
          event_type: String,
          marker: String
        ) -> Dry::Monads::Result
      end
    end
  end
end
