module Coordinator
  module Write
    module HistoryMigrations
      class LegacyWorkIntentionMembershipV1 < Shared::Value
        def reference: () -> LeaseReferenceV2
        def membership_event: () -> PgEventstore::Event
        def acquisition_event: () -> PgEventstore::Event
        def acquisition: () -> Events::ResourceLeaseAcquiredV2
      end
    end
  end
end
