module Coordinator
  module Write
    module HistoryMigrations
      class MergeSnapshotContextResolver
        def initialize: (
          event_store: EventStore,
          stream_identity_allocator: StreamIdentityAllocator,
          entity_reference_resolver: LegacyEntityReferenceResolver,
          candidate_context_resolver: CandidateContextResolver,
          target_event_reference_resolver: LegacyTargetEventReferenceResolver,
          ?schema_registry: LegacyEventSchemaRegistry
        ) -> void

        def from_registration: (
          migration_id: String,
          source_config_name: String,
          source_upper_position: Integer,
          source_event: PgEventstore::Event,
          source_registration: Events::MergeSnapshotRegisteredV1
        ) -> Dry::Monads::Result

        def from_stream: (
          migration_id: String,
          source_config_name: String,
          source_upper_position: Integer,
          source_event: PgEventstore::Event
        ) -> Dry::Monads::Result

        def from_reference: (
          migration_id: String,
          source_config_name: String,
          source_upper_position: Integer,
          source_event: PgEventstore::Event,
          source_reference: EventReference
        ) -> Dry::Monads::Result
      end
    end
  end
end
