module Coordinator
  module Write
    module HistoryMigrations
      class OperationBatchMigrationContextV1 < Shared::Value
        def source_creation: () -> LegacyEvents::OperationBatchCreatedV1
        def source_creation_event: () -> PgEventstore::Event
        def target_stream: () -> StreamReference
        def batch_id: () -> String
        def items: () -> Array[OperationBatchItemMigrationV1]
        def item: (Integer index) -> OperationBatchItemMigrationV1?
        def markers: () -> Array[String]
        def item_markers: (Integer index) -> Array[String]
      end
    end
  end
end
