module Coordinator
  module Write
    module HistoryMigrations
      class PageDispatcher
        include Dry::Monads::Result::Mixin

        def initialize: (source_loader: PageSourceLoader, event_dispatcher: EventDispatcher) -> void
        def call: (migration: MigrationSnapshotV1, page: Domain::HistoryMigrationPages::State) -> Dry::Monads::Result
      end
    end
  end
end
