module Coordinator
  module Write
    module HistoryMigrations
      class PageLocationV1 < Shared::Value
        def page_id: () -> String
        def event: () -> PgEventstore::Event
        def marker: () -> String
      end
    end
  end
end
