module Coordinator
  module Write
    module HistoryMigrations
      class PageSourceLoader
        def initialize: (source_reader: SourceReader) -> void
        def call: (Domain::HistoryMigrationPages::State state) -> Array[PgEventstore::Event]
      end
    end
  end
end
