module Coordinator
  module Write
    module HistoryMigrations
      class PageLocator
        MARKER_PURPOSE: String

        def initialize: (event_store: EventStore, ?marker_codec: Shared::Markers::CodecV2, ?schema_registry: EventSchemaRegistry) -> void
        def call: (migration_id: String, from_position: Integer) -> Dry::Monads::Result
        def marker: (migration_id: String, from_position: Integer) -> Dry::Monads::Result
      end
    end
  end
end
