module Coordinator
  module Write
    module HistoryMigrations
      class PostRemodelWorkIntentionContextV1 < Shared::Value
        def target_stream: () -> StreamReference
        def intention_id: () -> String
        def set: () -> PostRemodelWorkIntentionSetContextV1
        def resource_id: () -> String
        def resource_kind: () -> String
        def resource_path: () -> String
      end
    end
  end
end
