module Coordinator
  module Write
    module HistoryMigrations
      class PostRemodelWorkIntentionSetContextV1 < Shared::Value
        def target_stream: () -> StreamReference
        def set_id: () -> String
        def repository_id: () -> String
        def change_set_id: () -> String
        def work_item_id: () -> String
        def attempt_id: () -> String
        def repository_markers: () -> Array[String]
      end
    end
  end
end
