module Coordinator
  module Write
    module HistoryMigrations
      class ReleaseSetMigrationContextV1 < Shared::Value
        def source_preparation: () -> Events::ReleaseSetPreparedV1
        def source_preparation_event: () -> PgEventstore::Event
        def target_stream: () -> StreamReference
        def release_set_id: () -> String
        def change_set_id: () -> String
        def members: () -> Array[ReleaseSetMemberMigrationV1]
        def source_preparation_reference: () -> EventReference
        def member: (String source_repository_id) -> ReleaseSetMemberMigrationV1?
        def markers: () -> Array[String]
      end
    end
  end
end
