module Coordinator
  module Write
    module HistoryMigrations
      class ReleaseSetMemberMigrationV1 < Shared::Value
        def source_member: () -> ReleaseSets::MemberEvidenceV1
        def target_member: () -> Events::ReleaseSetMemberAddedV1
        def source_repository_id: () -> String
        def target_repository_id: () -> String
      end
    end
  end
end
