module Coordinator
  module Write
    module HistoryMigrations
      class RepositoryRegisteredV1Transformer
        def initialize: (
          stream_identity_allocator: StreamIdentityAllocator,
          ?compound_marker_builder: Shared::CompoundMarkerBuilder,
          ?natural_key_marker: Repositories::NaturalKeyMarker
        ) -> void

        def call: (
          migration_id: String,
          source_config_name: String,
          source_event: PgEventstore::Event,
          source_payload: Events::RepositoryRegisteredV1
        ) -> Dry::Monads::Result
      end
    end
  end
end
