module Coordinator
  module Write
    module HistoryMigrations
      class SourceReader
        EVENT_TYPES: Array[String]
        SELECTION_EVENT_TYPES: Array[String]
        def initialize: (client: PgEventstore::Client) -> void
        def head_position: (?to_position: Integer?, ?source_command_ids: Array[String], ?source_after_position: Integer?) -> Integer?
        def page: (SourcePageCriteriaV1 criteria) -> Array[PgEventstore::Event]
        def stream_tail_position: (PgEventstore::Event event, to_position: Integer) -> Integer?
        private
        def event_types: (Array[String] command_ids) -> (Array[String] | Array[Hash[Symbol, String | Array[String]]])
      end
    end
  end
end
