module Coordinator
  module Write
    module HistoryMigrations
      class SourceEventSchemaRegistry
        POST_REMODEL_DEFINITIONS: Hash[[String, Integer], singleton(Events::Base)]
        DEFINITIONS: Hash[[String, Integer], singleton(Events::Base)]

        def initialize: (?registry: EventSchemaRegistry) -> void
        def fetch: (type: String, schema_version: Integer) -> singleton(Events::Base)
        def load: (type: String, schema_version: Integer, data: event_data) -> Events::Base
      end
    end
  end
end
