module Coordinator
  module Write
    module HistoryMigrations
      class StoreRegistry
        SOURCE_CONFIG_NAME: String
        TARGET_CONFIG_NAME: String

        def available?: (String config_name) -> bool
        def client: (String config_name) -> PgEventstore::Client
      end
    end
  end
end
