module Coordinator
  module Write
    module HistoryMigrations
      class TargetWriter
        def initialize: (event_store: EventStore) -> void
        def call: (planned_facts: Array[PlannedFactV1]) -> Dry::Monads::Result
      end
    end
  end
end
