module Coordinator
  module Write
    module HistoryMigrations
      class TargetEventPlanner
        MARKER_PURPOSE: String
        PLAN_EVENT_TYPES: Array[String]
        PLAN_HEAD: LatestEventReadCriteria

        def initialize: (
          event_store: EventStore,
          ?target_stream_plan_allocator: TargetStreamPlanAllocator,
          ?marker_codec: Shared::Markers::CodecV2,
          ?id_generator: Shared::IdGenerator,
          ?event_factory: EventFactory,
          ?schema_registry: EventSchemaRegistry
        ) -> void

        def call: (
          migration_id: String,
          source_event: PgEventstore::Event,
          transformation_step: String,
          target_stream: StreamReference,
          target_event_id: String,
          target_event_type: String,
          caused_by: PgEventstore::Event
        ) -> Dry::Monads::Result

        def find: (
          migration_id: String,
          source_event: PgEventstore::Event,
          transformation_step: String,
          target_stream: StreamReference,
          target_event_id: String,
          target_event_type: String
        ) -> Dry::Monads::Result
      end
    end
  end
end
