module Coordinator
  module Write
    module HistoryMigrations
      class TargetPlanBuilder
        PROCESS_RULE_VERSION: String

        def initialize: (
          process_step_planner: Coordinator::Processes::ProcessStepPlanner,
          target_event_planner: TargetEventPlanner
        ) -> void

        def call: (
          migration_id: String,
          source_event: PgEventstore::Event,
          transformed_facts: Array[TransformedFactV1]
        ) -> Dry::Monads::Result
      end
    end
  end
end
