module Coordinator
  module Write
    module HistoryMigrations
      class TransformerRegistry
        def initialize: (
          ?schema_registry: EventSchemaRegistry | LegacyEventSchemaRegistry,
          repository_registered_v1: RepositoryRegisteredV1Transformer,
          guidance_message_v1: GuidanceMessageV1Transformer,
          coordination_task_submitted_v2: CoordinationTaskSubmittedV2Transformer,
          coordination_task_lifecycle: CoordinationTaskLifecycleTransformer,
          command_completed_v1: CommandCompletedV1Transformer
        ) -> void

        def call: (
          migration_id: String,
          source_config_name: String,
          source_upper_position: Integer?,
          source_event: PgEventstore::Event
        ) -> Dry::Monads::Result
      end
    end
  end
end
