module Coordinator
  module Write
    module HistoryMigrations
      class TransformedFactV1 < Shared::Value
        def target_stream: () -> StreamReference
        def event: () -> Events::Base
        def markers: () -> Array[String]
        def step_name: () -> String
        def metadata_extension: () -> MigrationMetadataExtensionV1?
      end
    end
  end
end
