module Coordinator
  module Write
    module HistoryMigrations
      class VerificationObligationValidityScanContextV1 < Shared::Value
        def source_started: () -> Events::VerificationObligationValidityScanStartedV1
        def source_started_event: () -> PgEventstore::Event
        def target_started_event: () -> EventReference?
        def target_stream: () -> StreamReference
        def scan_id: () -> String
        def change_set_id: () -> String
        def superseding_partition_event: () -> EventReference
        def source_started_reference: () -> EventReference
        def markers: () -> Array[String]
        def start_markers: () -> Array[String]
      end
    end
  end
end
