module Coordinator
  module Write
    module HistoryMigrations
      class VerificationPolicyV1Transformer
        def initialize: (
          partition_reference_resolver: DecisionPartitionEventReferenceResolver,
          head_reference_resolver: DecisionHeadReferenceResolver
        ) -> void

        def call: (
          migration_id: String,
          source_config_name: String,
          source_upper_position: Integer,
          source_event: PgEventstore::Event,
          policy: CandidateObligations::ImpactPolicyEvidenceV1,
          source_change_set_id: String,
          target_change_set_id: String
        ) -> Dry::Monads::Result
      end
    end
  end
end
