module Coordinator
  module Write
    module HistoryMigrations
      class WorkIntentionV1Transformer
        LEGACY_PURPOSE: String

        def initialize: (
          event_store: EventStore,
          context_resolver: WorkIntentionContextResolver,
          ?repository_marker_builder: RepositoryMarkerBuilder
        ) -> void

        def call: (
          migration_id: String,
          source_config_name: String,
          source_upper_position: Integer,
          source_event: PgEventstore::Event,
          source_payload: Events::Base
        ) -> Dry::Monads::Result
      end
    end
  end
end
