module Coordinator::Write::ReleaseSets
  class IntegrationFactV1 < Coordinator::Shared::Value
    def payload: () -> Coordinator::Write::Events::RepositoryIntegrationRecordedV1
    def event: () -> Coordinator::Write::EventReference
  end
end
