module Coordinator
  module Write
    module Domain
      module HistoryMigrationPages
        class Apply
          include Dry::Monads::Result::Mixin

          def initialize: (?stream_factory: StreamFactory) -> void
          def call: (state: State, command: Commands::ApplyHistoryMigrationPage) -> Dry::Monads::Result
        end
      end
    end
  end
end
