module Coordinator
  module Write
    module Domain
      module HistoryMigrationPages
        class Create
          include Dry::Monads::Result::Mixin

          def initialize: (?stream_factory: StreamFactory) -> void
          def call: (state: State, command: Commands::CreateHistoryMigrationPage) -> Dry::Monads::Result
        end
      end
    end
  end
end
