module Coordinator
  module Read
    module Projections
      class CoordContextStateLoader
        def call: (Hash[String | Symbol, untyped] document) -> CoordContextStateV1
      end
    end
  end
end
