query Projects(
  $search: String
  $sort: ProjectSort
  $first: Int
  $after: String
  $repositoriesFirst: Int
) {
  projects(
    search: $search
    sort: $sort
    first: $first
    after: $after
    repositoriesFirst: $repositoriesFirst
  ) {
    nodes {
      projectRef
      displayLabel
      repositoryCount
      scope
      repositories {
        nodes {
          id
          displayName
          paths
        }
        totalCount
        pageInfo {
          hasNextPage
        }
      }
    }
    pageInfo {
      endCursor
      hasNextPage
    }
  }
}
