module Coordinator
  module Processes
    module VerificationObligationValidity
      class PageV1 < Shared::Value
        def obligations: () -> Array[PgEventstore::Event]
        def last_processed_position: () -> Integer?
        def has_more: () -> bool
      end
    end
  end
end
