module Coordinator
  module Read
    module Web
      module Queries
        class ProjectResources
          def initialize: (
            ?collection_contract: Contracts::ProjectResources::Collection,
            ?detail_contract: Contracts::ProjectResources::Detail,
            ?repository: Repositories::ProjectResources,
            ?resource_get: Read::Queries::ResourceGet,
            ?project_reference: ProjectReference,
            ?clock: Shared::_Clock
          ) -> void
          def resources: (command_input input) -> ProjectResourcesV1::ResourcePage?
          def resource: (command_input input) -> ProjectResourcesV1::Resource?
          def active_work_intentions: (command_input input) -> ProjectResourcesV1::WorkIntentionPage?
          def work_intention: (command_input input) -> ProjectResourcesV1::WorkIntention?
        end
      end
    end
  end
end
