module Coordinator
  module Write
    module Domain
      module Repositories
        class Register
          class DecisionV1 < Shared::Value
            Registration: untyped
            Plan: untyped

            def registration: () -> RepositoryRegistrationV2
            def event_plan: () -> EventPlan?
            def outcome: () -> String
          end

          def initialize: (?stream_factory: StreamFactory) -> void
          def call: (registration_by_key: RepositoryRegistrationV2?, registration_by_id: RepositoryRegistrationV2?, command: Commands::RegisterRepository) -> Dry::Monads::Result
        end
      end
    end
  end
end
