module Coordinator
  module Write
    module Domain
      module Repositories
        class Register
          def initialize: (?stream_factory: StreamFactory) -> void
          def call: (registration: Events::RepositoryRegisteredV1?, command: Commands::RegisterRepository, registered_at: String) -> Dry::Monads::Result
        end
      end
    end
  end
end
