module Coordinator::Write::Domain::ReleaseSets
  class CompleteActivated
    include Dry::Monads::Result::Mixin

    def initialize: (?stream_factory: Coordinator::Write::StreamFactory) -> void
    def call: (state: LifecycleStateV2, command: Coordinator::Write::Commands::CompleteActivatedReleaseSet) -> Dry::Monads::Result
  end
end
