module Coordinator::Write::Domain::ReleaseSets
  class Prepare
    include Dry::Monads::Result::Mixin

    def initialize: (?stream_factory: Coordinator::Write::StreamFactory) -> void
    def call: (state: PreparationStateV1, command: Coordinator::Write::Commands::PrepareReleaseSet) -> Dry::Monads::Result
  end
end
