module Coordinator::Write::Domain::ReleaseSets
  class RecordVerification
    include Dry::Monads::Result::Mixin

    def initialize: (?stream_factory: Coordinator::Write::StreamFactory) -> void
    def call: (state: LifecycleStateV2, command: Coordinator::Write::Commands::RecordReleaseSetVerification) -> Dry::Monads::Result
  end
end
