module Coordinator
  module Write
    module Operations
      class ExecutePlanHistoryMigrationPage
        EVENT_TYPES: Array[String]

        def initialize: (event_store: EventStore, ?loader: HistoryMigrations::PageLoader, ?decider: Domain::HistoryMigrationPages::Plan, ?id_generator: Shared::IdGenerator, ?event_factory: EventFactory, ?stream_factory: StreamFactory) -> void
        def call_command: (Commands::PlanHistoryMigrationPage command, caused_by: PgEventstore::Event) -> Dry::Monads::Result
      end
    end
  end
end
