module Coordinator
  module Write
    module Operations
      class ExecuteOperationBatchCommand
        def initialize: (event_store: _EventStore, ?loader: OperationBatches::Loader, ?decider: OperationBatches::Decider, ?input_digest: CommandInputDigest, ?id_generator: Shared::_IdGenerator, ?event_factory: EventFactory, ?schema_registry: EventSchemaRegistry, ?stream_factory: StreamFactory, ?completion_builder: CommandResultBuilder, ?outcome_contract: Contracts::OperationBatchItemOutcome, ?command_loader: CommandLifecycle::Loader, ?request_marker: CommandLifecycle::RequestMarker, ?target_builder: Tasks::TargetCommandBuilder, ?manifest_builder: OperationBatches::ManifestBuilder) -> void
        def call_command: (Commands::CreateOperationBatch | Commands::CancelOperationBatch | Commands::RecordOperationBatchItemOutcome | Commands::RequestOperationBatchContinuation | Commands::CompleteOperationBatch | Commands::CompleteOperationBatchCancellation command, ?caused_by: PgEventstore::Event?) -> Dry::Monads::Result
      end
    end
  end
end
