module Coordinator
  module Write
    module Operations
      class ExecuteReleaseLeaseSet
        def initialize: (event_store: _EventStore, ?preparer: PrepareReleaseLeaseSet, ?decider: Domain::ResourceLeases::Release, ?input_digest: CommandInputDigest, ?clock: Shared::_Clock, ?id_generator: Shared::_IdGenerator, ?event_factory: EventFactory, ?schema_registry: EventSchemaRegistry, ?stream_factory: StreamFactory, ?completion_builder: CommandCompletionBuilder, ?compound_marker_builder: Shared::CompoundMarkerBuilder, ?repository_registration_loader: RepositoryRegistrationLoader, ?repository_marker_builder: RepositoryMarkerBuilder, ?event_plan_contract: Contracts::WriteSetReleaseEventPlan) -> void
        %a{rbs:test:skip}
        def call: (command_input input) -> Dry::Monads::Result
        def call_command: (Commands::ReleaseLeaseSet command, ?caused_by: PgEventstore::Event?) -> Dry::Monads::Result
      end
    end
  end
end
