module Coordinator
  module Write
    module Operations
      class ExecuteCompleteHistoryMigrationPlan
        def initialize: (event_store: EventStore, ?loader: HistoryMigrations::MigrationLoader, ?decider: Domain::HistoryMigrations::CompletePlan, ?id_generator: Shared::IdGenerator, ?event_factory: EventFactory, ?stream_factory: StreamFactory) -> void
        def call_command: (Commands::CompleteHistoryMigrationPlan command, caused_by: PgEventstore::Event) -> Dry::Monads::Result
      end
    end
  end
end
