module Coordinator
  module Write
    module Operations
      class ExecuteDeclareDevelopmentArtifactRelation
        TOOL_NAME: String
        def initialize: (event_store: _EventStore, ?preparer: PrepareDeclareDevelopmentArtifactRelation, ?loader: DevelopmentArtifacts::Loader, ?target_resolver: DevelopmentArtifacts::RelationTargetResolver, ?decider: Domain::DevelopmentArtifacts::DeclareRelation, ?input_digest: CommandInputDigest, ?clock: Shared::_Clock, ?id_generator: Shared::_IdGenerator, ?event_factory: EventFactory, ?schema_registry: EventSchemaRegistry, ?stream_factory: StreamFactory, ?marker_builder: DevelopmentArtifacts::MarkerBuilder, ?completion_builder: CommandCompletionBuilder) -> void
        %a{rbs:test:skip}
        def call: (command_input input) -> Dry::Monads::Result
        def call_command: (Commands::DeclareDevelopmentArtifactRelation command, ?caused_by: PgEventstore::Event?) -> Dry::Monads::Result
      end
    end
  end
end
