module Coordinator::Write::Operations
  class ExecuteRecordReleaseSetActivation < Dry::Operation
    TOOL_NAME: String
    def initialize: (event_store: Coordinator::Write::_EventStore, ?preparer: PrepareRecordReleaseSetActivation, ?history_loader: Coordinator::Write::ReleaseSets::HistoryLoader, ?decider: Coordinator::Write::Domain::ReleaseSets::RecordActivation, ?digest_builder: Coordinator::Write::ReleaseSets::ActivationDigestBuilder, ?input_digest: Coordinator::Write::CommandInputDigest, ?clock: Coordinator::Shared::_Clock, ?id_generator: Coordinator::Shared::_IdGenerator, ?event_factory: Coordinator::Write::EventFactory, ?stream_factory: Coordinator::Write::StreamFactory, ?completion_builder: Coordinator::Write::CommandResultBuilder, ?event_plan_contract: Coordinator::Write::Contracts::ReleaseSetActivationEventPlan) -> void
    %a{rbs:test:skip}
    def call: (Coordinator::Write::command_input input) -> Dry::Monads::Result
    def call_command: (Coordinator::Write::Commands::RecordReleaseSetActivation command, ?caused_by: PgEventstore::Event?) -> Dry::Monads::Result
  end
end
