module Coordinator::Write::Operations
  class ExecuteRecordMergeObservation < Dry::Operation
    TOOL_NAME: String

    def initialize: (event_store: Coordinator::Write::_EventStore, ?preparer: PrepareRecordMergeObservation, ?evaluator: Coordinator::Write::MergeAuthorizations::Evaluator, ?decider: Coordinator::Write::Domain::MergeObservations::Record, ?input_digest: Coordinator::Write::CommandInputDigest, ?observation_digest_builder: Coordinator::Write::MergeObservations::ObservationDigestBuilder, ?clock: Coordinator::Shared::_Clock, ?id_generator: Coordinator::Shared::_IdGenerator, ?event_factory: Coordinator::Write::EventFactory, ?schema_registry: Coordinator::Write::EventSchemaRegistry, ?stream_factory: Coordinator::Write::StreamFactory, ?completion_builder: Coordinator::Write::CommandResultBuilder, ?event_plan_contract: Coordinator::Write::Contracts::MergeObservationEventPlan) -> void
    %a{rbs:test:skip}
    def call: (Coordinator::Write::command_input input) -> Dry::Monads::Result
    def call_command: (Coordinator::Write::Commands::RecordMergeObservation command, ?caused_by: PgEventstore::Event?) -> Dry::Monads::Result
  end
end
