module Coordinator
  module Write
    module Operations
      class ExecuteCreateChangeSet
        def initialize: (event_store: _EventStore, ?preparer: PrepareCreateChangeSet, ?decider: Domain::ChangeSets::Create, ?input_digest: CommandInputDigest, ?clock: Shared::_Clock, ?id_generator: Shared::_IdGenerator, ?event_factory: EventFactory, ?schema_registry: EventSchemaRegistry, ?stream_factory: StreamFactory, ?completion_builder: CommandCompletionBuilder) -> void
        %a{rbs:test:skip}
        def call: (command_input input) -> untyped
      end
    end
  end
end
