module Coordinator
  module Write
    module Operations
      class ExecuteExpireWorkIntention
        TOOL_NAME: String

        def initialize: (
          event_store: _EventStore,
          ?decider: Domain::WorkIntentions::Expire,
          ?input_digest: CommandInputDigest,
          ?clock: Shared::_Clock,
          ?id_generator: Shared::_IdGenerator,
          ?event_factory: EventFactory,
          ?stream_factory: StreamFactory,
          ?completion_builder: CommandResultBuilder,
          ?repository_registration_loader: RepositoryRegistrationLoader,
          ?repository_marker_builder: RepositoryMarkerBuilder,
          ?resource_loader: WorkIntentionResourceLoader,
          ?intention_loader: WorkIntentionLoader
        ) -> void

        %a{rbs:test:skip}
        def call: (Commands::ExpireWorkIntention command, caused_by: PgEventstore::Event) -> Dry::Monads::Result
        def call_command: (Commands::ExpireWorkIntention command, caused_by: PgEventstore::Event) -> Dry::Monads::Result
      end
    end
  end
end
