module Coordinator
  module Write
    module Operations
      class ExecuteCompleteHistoryMigration
        include Dry::Monads::Result::Mixin

        def initialize: (event_store: _EventStore, ?loader: HistoryMigrations::MigrationLoader, ?decider: Domain::HistoryMigrations::Complete, ?id_generator: Shared::IdGenerator, ?event_factory: EventFactory, ?stream_factory: StreamFactory) -> void
        def call_command: (Commands::CompleteHistoryMigration command, caused_by: PgEventstore::Event) -> Dry::Monads::Result
      end
    end
  end
end
