module Coordinator
  module Write
    module Operations
      class GetCoordinationTask
        def initialize: (loader: Tasks::Loader) -> void
        def call: (task_id: String) -> Dry::Monads::Result
      end
    end
  end
end
