module Coordinator
  module Write
    module Operations
      class PrepareStartHistoryMigration
        def initialize: (
          ?contract: Contracts::StartHistoryMigration,
          ?store_registry: HistoryMigrations::StoreRegistry,
          ?id_generator: Shared::IdGenerator
        ) -> void
        %a{rbs:test:skip}
        def call: (command_input input) -> Dry::Monads::Result
      end
    end
  end
end
