module Coordinator
  module Write
    module Operations
      class PrepareReserveWriteSet
        def initialize: (?contract: Contracts::ReserveWriteSet, ?git_object_ids_contract: Contracts::GitObjectIds) -> void
        %a{rbs:test:skip}
        def call: (command_input input) -> Dry::Monads::Result
        def scope_for_repository: (Commands::ReserveWriteSet command, repository_registration: Events::RepositoryRegisteredV1) -> Dry::Monads::Result
      end
    end
  end
end
