module Coordinator
  module Write
    module Operations
      class PrepareRecordAgentChoice < Dry::Operation
        def initialize: (?contract: Contracts::RecordAgentChoice) -> void
        %a{rbs:test:skip}
        def call: (command_input input) -> Dry::Monads::Result
      end
    end
  end
end
