module Coordinator
  module Write
    module Operations
      class PrepareActivateDecision < Dry::Operation
        def initialize: (?contract: Contracts::ActivateDecision) -> void
        %a{rbs:test:skip}
        def call: (command_input input) -> Dry::Monads::Result
      end
    end
  end
end
