module Coordinator
  module Write
    module Operations
      class PrepareDeclareWorkIntentionSet
        def initialize: (?contract: Contracts::DeclareWorkIntentionSet, ?git_object_ids_contract: Contracts::GitObjectIds) -> void
        %a{rbs:test:skip}
        def call: (command_input input) -> Dry::Monads::Result
      end
    end
  end
end
