module Coordinator
  module Write
    module Operations
      class StartCoordinationTask
        def initialize: (transition: ApplyCoordinationTaskTransition, ?decider: Domain::CoordinationTasks::Start, ?clock: Shared::SystemClock) -> void
        def call: (task_id: String, ?caused_by: PgEventstore::Event?) -> Dry::Monads::Result
      end
    end
  end
end
