module Coordinator
  module Processes
    module OperationBatches
      class CommandBuilder
        SYSTEM_ACTOR: Write::Commands::Actor

        def record_outcome: (source: SourceV1, item: Write::OperationBatches::ItemV2, execution: Write::Tasks::TargetExecution, command_id: String) -> Write::Commands::RecordOperationBatchItemOutcome
        def continuation: (source: SourceV1, page_start: Integer, page_end: Integer, command_id: String) -> Write::Commands::RequestOperationBatchContinuation
        def complete: (source: SourceV1, command_id: String) -> Write::Commands::CompleteOperationBatch
        def complete_cancellation: (source: SourceV1, command_id: String) -> Write::Commands::CompleteOperationBatchCancellation
      end
    end
  end
end
