module Coordinator
  module Processes
    module OperationBatches
      type source_payload = Write::Events::OperationBatchCreatedV2 | Write::Events::OperationBatchContinuationRequestedV2 | Write::Events::OperationBatchCancellationRequestedV2

      class SourceV1 < Shared::Value
        def event: () -> PgEventstore::Event
        def payload: () -> source_payload
        def reference: () -> Write::EventReference
      end
    end
  end
end
