module Coordinator
  module Processes
    module OperationBatches
      class TargetCompletionV1 < Shared::Value
        def event: () -> PgEventstore::Event
        def payload: () -> Write::Events::CommandCompletedV1
        def reference: () -> Write::EventReference
      end
    end
  end
end
