module Coordinator
  module Write
    module Skills
      class AssetBuilder
        def initialize: (?content_builder: Content::Builder) -> void
        def call: (Hash[Symbol, untyped] attributes) -> Dry::Monads::Result
      end
    end
  end
end
