module Coordinator
  module Write
    module Skills
      class IdentityBuilder
        def initialize: (?id_generator: Shared::IdGenerator) -> void
        def call: (name: String, scope: String) -> IdentityV1
      end
    end
  end
end
