module Coordinator
  module Read
    module Web
      module Repositories
        class ProjectResources
          def resources: (ProjectResourcesQueryV1::Collection query) -> ProjectResourcesV1::ResourcePage?
          def resource: (ProjectResourcesQueryV1::Detail query, ResourceViewV1 view) -> ProjectResourcesV1::Resource?
          def active_work_intentions: (ProjectResourcesQueryV1::Collection query) -> ProjectResourcesV1::WorkIntentionPage?
          def work_intention: (ProjectResourcesQueryV1::Detail query) -> ProjectResourcesV1::WorkIntention?
        end
      end
    end
  end
end
