module Coordinator
  module Write
    module Domain
      module ResourceLeases
        class Reserve
          def initialize: (?stream_factory: StreamFactory) -> void
          def call: (attempt_state: Domain::Attempts::State, lease_states: Array[State], command: Commands::ReserveWriteSet, lease_set_id: String, lease_ids: Array[String], acquired_at: String, expires_at: String) -> Dry::Monads::Result
        end
      end
    end
  end
end
