module Coordinator
  module Write
    module Domain
      module Candidates
        class SubmissionState < Coordinator::Shared::Value
          attr_reader existing_candidate: Coordinator::Write::EventReference?
          attr_reader existing_head: Coordinator::Write::EventReference?
          attr_reader attempt: Coordinator::Write::Domain::Attempts::State
          attr_reader intention_set: Coordinator::Write::Domain::WorkIntentions::SetState?
          attr_reader current_intentions: Array[Coordinator::Write::WorkIntentionObservationV1]
        end
      end
    end
  end
end
