module Coordinator
  module Write
    module Domain
      module OperationBatches
        class Create
          def initialize: (?stream_factory: StreamFactory) -> void
          def call: (state: Write::OperationBatches::State, command: Commands::CreateOperationBatch, items: Array[Write::OperationBatches::ItemV2]) -> Dry::Monads::Result
        end
      end
    end
  end
end
