module Coordinator
  module Read
    module Contracts
      class CandidateSourceEvent < Dry::Validation::Contract
        REVISION_BY_EVENT_TYPE: Hash[String, Integer]
        EVENT_TYPES: Array[String]

        def call: (Hash[Symbol, untyped] input) -> Dry::Validation::Result
      end
    end
  end
end
