module Coordinator
  module Read
    module Contracts
      class DecisionGet < Dry::Validation::Contract
        def call: (Write::command_input input) -> Dry::Validation::Result
      end
    end
  end
end
