module Coordinator
  module Read
    module Contracts
      class DecisionGovernanceSourceEvent < Dry::Validation::Contract
        EVENT_SCHEMAS: Hash[String, [String, Array[Integer]]]
        EVENT_TYPES: Array[String]

        def call: (Hash[Symbol, untyped] input) -> Dry::Validation::Result
      end
    end
  end
end
