module Coordinator
  module Read
    module Contracts
      class GuidanceSourceEvent
        EVENT_TYPES: Array[String]
        EVENT_SCHEMAS: Hash[String, Array[Integer]]

        def call: (command_input input) -> Dry::Validation::Result
      end
    end
  end
end
