module Coordinator
  module Read
    module Contracts
      class VerificationOutcomeProjection < Dry::Validation::Contract
        Outcome: untyped

        def call: (command_input input) -> Dry::Validation::Result
      end
    end
  end
end
