module Coordinator
  module Write
    module VerificationObligationValidityScans
      class ScanIdentityDocumentV1 < Shared::Value
        def schema: () -> String
        def superseding_partition_event: () -> EventReference
        def rule_version: () -> String
      end
    end
  end
end
