module Coordinator
  module Read
    module Web
      module Contracts
        class CoordinationDashboard
          PRESENTATION_STATUSES: Array[String]

          class Page < Dry::Validation::Contract
          end

          class Detail < Dry::Validation::Contract
          end
        end
      end
    end
  end
end
