module Coordinator
  module Read
    module Web
      module Contracts
        class GovernanceBrowser
          class Decisions < Dry::Validation::Contract
          end

          class GuidanceList < Dry::Validation::Contract
          end

          class Choices < Dry::Validation::Contract
          end

          class Impacts < Dry::Validation::Contract
          end

          class Decision < Dry::Validation::Contract
          end

          class Guidance < Dry::Validation::Contract
          end

          class Choice < Dry::Validation::Contract
          end

          class Impact < Dry::Validation::Contract
          end

          class Receipts < Dry::Validation::Contract
          end

          class Receipt < Dry::Validation::Contract
          end

          class CommandCompletion < Dry::Validation::Contract
          end
        end
      end
    end
  end
end
