module Coordinator::Processes::ReleaseSetLifecycle
  class CommandBuilder
    ACTOR: Coordinator::Write::Commands::Actor
    COMPENSATION_RULE_VERSION: String
    COMPLETION_RULE_VERSION: String
    def call: (SourceV1 source) -> (Coordinator::Write::Commands::RequestReleaseSetCompensation | Coordinator::Write::Commands::CompleteActivatedReleaseSet)?
  end
end
