module Coordinator
  module Write
    module Domain
      module ChangeSets
        class Activate
          def initialize: (?stream_factory: StreamFactory) -> void
          def call: (state: State, command: Commands::ActivateChangeSet, occurred_at: String) -> untyped
        end
      end
    end
  end
end
