module Coordinator::Read::Repositories
  class MergeAuthorizations
    def latest_for: (String merge_snapshot_id) -> Coordinator::Read::MergeAuthorizationViewV1?
    def store: (event: PgEventstore::Event, decision: Coordinator::Write::Events::MergeAuthorizationGrantedV1 | Coordinator::Write::Events::MergeAuthorizationDeniedV1) -> Coordinator::Read::MergeAuthorization
  end
end
