module Coordinator
  module Read
    module Repositories
      class OperationBatches
        def initialize: (?arguments_builder: OperationBatchArguments) -> void
        def fetch: (OperationBatchGetQueryV1 query) -> OperationBatchViewV1?
        def store: (event: PgEventstore::Event, payload: Write::Events::OperationBatchCreatedV2 | Write::Events::OperationBatchTargetSelectedV1 | Write::Events::OperationBatchItemEnqueuedV1 | Write::Events::OperationBatchItemSucceededV2 | Write::Events::OperationBatchItemRejectedV2 | Write::Events::OperationBatchItemCompletionLinkedV1 | Write::Events::OperationBatchContinuationRequestedV2 | Write::Events::OperationBatchCancellationRequestedV2 | Write::Events::OperationBatchCancelledV2 | Write::Events::OperationBatchCompletedV2) -> untyped
      end
    end
  end
end
