module Coordinator
  module Write
    module Domain
      module Guidance
        class State < Shared::Value
          EVENT_CLASSES: Array[
            singleton(Events::UserUtteranceRecordedV2) |
            singleton(Events::UserUtteranceForwardedByAgentV2)
          ]

          def message_id: () -> String?
          def self.initial: () -> State
          def self.reduce: (Array[Events::Base]) -> State
          def absent?: () -> bool
          def apply: (Events::Base) -> State
        end
      end
    end
  end
end
