module Coordinator
  module Write
    module Content
      class TextV1 < Shared::Value
        def encoding: () -> String
        def media_type: () -> String
        def text: () -> String
        def content_sha256: () -> String
        def byte_size: () -> Integer
      end
    end
  end
end
