module Coordinator
  module Read
    module DecisionResolution
      class PartitionSelector
        def call: (QueryContextV1 context, topic_id: String) -> Array[Write::Decisions::DecisionPartitionV1]
      end
    end
  end
end
