module Coordinator
  module Read
    module Web
      class CoordinationDashboardQueryV1 < Shared::Value
        def repository_id: () -> String
        def first: () -> Integer
        def change_set_offset: () -> Integer
        def work_item_offset: () -> Integer
        def dependency_offset: () -> Integer
        def presentation_statuses: () -> Array[String]
        def work_item_sort: () -> String
        def blocking: () -> bool?
      end
    end
  end
end
