module Coordinator
  module Read
    module Web
      class DeliveryBrowserQueryError < StandardError
        attr_reader details: Hash[Symbol?, untyped]
        def initialize: (Hash[Symbol?, untyped] details) -> void
      end
    end
  end
end
