module Coordinator
  module Read
    module Web
      class KnowledgeBrowserV1
        class SkillDetail < Shared::Value
          def skill: () -> Read::SkillViewV1
        end

        class SkillAssetDetail < Shared::Value
          def asset: () -> (Read::SkillTextAssetViewV2 | Read::SkillBinaryAssetViewV2)
        end

        class ArtifactDetail < Shared::Value
          def artifact: () -> Read::DevelopmentArtifactSummaryV1
          def content: () -> (Read::DevelopmentArtifactTextContentViewV2 | Read::DevelopmentArtifactBinaryContentViewV2)
        end

        class ArtifactRelationships < Shared::Value
          def artifact: () -> Read::DevelopmentArtifactSummaryV1
          def relationships: () -> Read::DevelopmentArtifactRelationPageV1
        end
      end
    end
  end
end
