module Coordinator::Write::MergeSnapshots
  class CandidateHistoryV1 < Coordinator::Shared::Value
    attr_reader requested: RequestedCandidateV1
    attr_reader candidate: Coordinator::Write::Candidates::StateV2?
    attr_reader manifest: Coordinator::Write::Events::CandidateChangeManifestCapturedV2?
    attr_reader candidate_event: Coordinator::Write::EventReference?
    attr_reader manifest_event: Coordinator::Write::EventReference?
  end
end
