module Coordinator::Write::MergeSnapshots
  class CandidateLoader
    def initialize: (event_store: Coordinator::Write::_EventStore, ?state_loader: Coordinator::Write::Candidates::StateLoader, ?contract: Coordinator::Write::Contracts::MergeSnapshotCandidateHistory) -> void
    def call: (RequestedCandidateV1 requested) -> CandidateHistoryV1

  end
end
