module Coordinator
  module Processes
    module Contracts
      class ChangeSetActivationSourceEvent
        def call: ({ event: PgEventstore::Event } input) -> Dry::Validation::Result
      end
    end
  end
end
