module Coordinator
  module Processes
    module Contracts
      class CoordinationTaskSourceEvent < Dry::Validation::Contract
        def initialize: (?execution_lane: Write::Tasks::ExecutionLane) -> void
      end
    end
  end
end
