module Coordinator
  module Processes
    module Contracts
      class HistoryMigrationSourceEvent < Dry::Validation::Contract
        STREAM_BY_TYPE: Hash[String, Array[String]]
      end
    end
  end
end
