module Coordinator
  module Shared
    module Subscriptions
      class Definition < Value
        include _SubscriptionDefinition

        def set_name: () -> String
        def stream_context: () -> String
        def stream_name: () -> String
        def event_type: () -> String
        def identity: () -> Identity
      end
    end
  end
end
