module Coordinator
  module Write
    module Events
      class ChangeSetAcceptanceCriteriaDefinedV1 < Base
        def change_set_id: () -> String
        def acceptance_criteria: () -> Array[String]
        def defined_at: () -> String
      end
    end
  end
end
