module Coordinator
  module Write
    module Events
      class CommandRejectedV2 < Base
        def command_id: () -> String
        def error: () -> (Tasks::DomainErrorV1::domain_error)
        def retryable: () -> bool
      end
    end
  end
end
