module Coordinator
  module Write
    module Events
      class CoordinationTaskFailedV1 < Base
        def task_id: () -> String
        def error: () -> Tasks::JsonRpcErrorV1
        def failed_at: () -> String
      end
    end
  end
end
