module Coordinator
  module Write
    module Events
      class CoordinationTaskExecutionStartedV1 < Base
        def task_id: () -> String
        def started_at: () -> String
      end
    end
  end
end
