module Coordinator
  module Write
    module Events
      class CoordinationTaskSubmittedV3 < Base
        def task_id: () -> String
        def command_id: () -> String
        def tool_name: () -> String
        def command_input: () -> CommandInputDocuments::value
        def poll_interval_ms: () -> Integer
        def ttl_ms: () -> nil
      end
    end
  end
end
