module Coordinator
  module Write
    module Events
      class DevelopmentArtifactCapturedV1 < Base
        def artifact: () -> DevelopmentArtifacts::ArtifactV1
        def captured_at: () -> String
      end
    end
  end
end
