module Coordinator
  module Write
    module Events
      class DevelopmentArtifactCapturedV2 < Base
        def artifact: () -> DevelopmentArtifacts::ArtifactV2
        def captured_at: () -> String
      end
    end
  end
end
