module Coordinator
  module Write
    module Events
      class DevelopmentArtifactRelationDeclaredV1 < Base
        def artifact_relation: () -> DevelopmentArtifacts::RelationV1
        def declared_at: () -> String
      end
    end
  end
end
