module Coordinator
  module Write
    module Events
      class HistoryMigrationCorrelationAllocatedV1 < Base
        def migration_id: () -> String
        def source_config_name: () -> String
        def source_correlation_id: () -> String
        def target_correlation_id: () -> String
      end
    end
  end
end
