module Coordinator
  module Write
    module Events
      class HistoryMigrationPageSourceEventCountRecordedV1 < Base
        attr_reader page_id: String
        attr_reader source_event_count: Integer
      end
    end
  end
end
