module Coordinator
  module Write
    module Events
      class HistoryMigrationStreamIdentityAllocatedV1 < Base
        def migration_id: () -> String
        def source_config_name: () -> String
        def source_stream_context: () -> String
        def source_stream_name: () -> String
        def source_stream_id: () -> String
        def source_stream_starting_position: () -> Integer
        def target_stream_context: () -> String
        def target_stream_name: () -> String
        def identity_role: () -> String
        def target_stream_id: () -> String
      end
    end
  end
end
