module Coordinator
  module Write
    module Events
      class HistoryMigrationTargetEventPlannedV1 < Base
        def migration_id: () -> String
        def plan_id: () -> String
        def source_event_id: () -> String
        def source_global_position: () -> Integer
        def transformation_step: () -> String
        def dependency_wave: () -> Integer
        def target_event: () -> EventReference
      end
    end
  end
end
