module Coordinator
  module Write
    module Events
      class HistoryMigrationPageDependencyWaveAppliedV1 < Base
        attr_reader page_id: String
        attr_reader dependency_wave: Integer
        attr_reader target_event_count: Integer
      end
    end
  end
end
