module Coordinator
  module Write
    module Events
      class HistoryMigrationCursorAdvancedV1 < Base
        attr_reader migration_id: String
        attr_reader next_from_position: Integer
      end
    end
  end
end
