module Coordinator
  module Write
    module Events
      class HistoryMigrationTargetStreamPlanCreatedV1 < Base
        def migration_id: () -> String
        def plan_id: () -> String
        def target_stream_context: () -> String
        def target_stream_name: () -> String
        def target_stream_id: () -> String
      end
    end
  end
end
