module Coordinator
  module Write
    module Events
      class HistoryMigrationSourceRangeFrozenV1 < Base
        def migration_id: () -> String
        def source_upper_position: () -> Integer?
      end
    end
  end
end
