module Coordinator
  module Write
    module Events
      class HistoryMigrationTargetStoreSelectedV1 < Base
        def migration_id: () -> String
        def target_config_name: () -> String
      end
    end
  end
end
