module Coordinator
  module Write
    module Events
      class HistoryMigrationSourceSelectionFrozenV1 < Base
        def migration_id: () -> String
        def source_after_position: () -> Integer
        def source_command_ids: () -> Array[String]
      end
    end
  end
end
