module Coordinator
  module Write
    module Events
      class OperationBatchContinuationRequestedV1 < Base
        def batch_id: () -> String
        def page_start: () -> Integer
        def page_end: () -> Integer
        def source_event: () -> EventReference
        def requested_at: () -> String
      end
    end
  end
end
