module Coordinator
  module Write
    module Events
      class OperationBatchCancellationRequestedV1 < Base
        def batch_id: () -> String
        def requester: () -> OperationBatches::ActorV1
        def requested_at: () -> String
      end
    end
  end
end
