module Coordinator
  module Write
    module Events
      class RepositoryRegisteredV1 < Base
        def repository_id: () -> String
        def scope: () -> String
        def repository_key: () -> String?
        def display_name: () -> String?
        def paths: () -> Array[String]
        def remotes: () -> Array[String]
        def registered_at: () -> String
      end
    end
  end
end
