module Coordinator
  module Write
    module Events
      class WorkItemCandidateSelectedV1 < Base
        def change_set_id: () -> String
        def work_item_id: () -> String
        def attempt_id: () -> String
        def candidate_id: () -> String
        def candidate_event: () -> EventReference
        def selected_at: () -> String
      end
    end
  end
end
