module Coordinator
  module Write
    module Events
      class WorkItemAssignedToRepositoryV1 < Base
        def work_item_id: () -> String
        def repository_id: () -> String
      end
    end
  end
end
