module Coordinator
  module Write
    module Events
      class WorkItemMadeReadyV1 < Base
        def change_set_id: () -> String
        def work_item_id: () -> String
        def readiness_decision_id: () -> String
        def reason: () -> String
        def made_ready_at: () -> String
      end
    end
  end
end
