module Coordinator
  module Write
    module Events
      class WorkItemDependencyDeclaredV1 < Base
        def change_set_id: () -> String
        def dependency_id: () -> String
        def producer_work_item_id: () -> String
        def consumer_work_item_id: () -> String
        def dependency_kind: () -> String
        def required_output: () -> RequiredOutput?
        def declared_at: () -> String
      end
    end
  end
end
