module Coordinator
  module Write
    module Events
      class WorkItemAcquiredV1 < Base
        def change_set_id: () -> String
        def work_item_id: () -> String
        def attempt_id: () -> String
        def agent_id: () -> String
        def acquired_at: () -> String
      end
    end
  end
end
