module Coordinator
  module Write
    module Events
      class WorkItemCompletedV1 < Base
        Output: singleton(WorkItemOutputV1)

        def change_set_id: () -> String
        def work_item_id: () -> String
        def attempt_id: () -> String
        def candidate_id: () -> String
        def candidate_event: () -> EventReference
        def produced_outputs: () -> Array[WorkItemOutputV1]
        def rule_version: () -> String
        def completed_at: () -> String
      end
    end
  end
end
