module Coordinator
  module Write
    module Events
      class WorkItemRequeuedV2 < Base
        def work_item_id: () -> String
        def change_set_id: () -> String
        def attempt_id: () -> String
        def agent_id: () -> String
        def reason: () -> String
      end
    end
  end
end
