module Coordinator::Processes::ProcessManagers
  class BuildProgress
    SOURCE_DEPENDENCY_KINDS: Hash[untyped, Array[String]]
    HANDLED_OUTCOME_CODES: Array[Symbol]
    def initialize: (event_store: Coordinator::Write::_EventStore, ?source_builder: Coordinator::Processes::BuildProgress::SourceBuilder, ?command_builder: Coordinator::Processes::BuildProgress::CommandBuilder, ?process_step_planner: Coordinator::Processes::ProcessStepPlanner, ?satisfy_dependency: Coordinator::Write::Operations::ExecuteSatisfyWorkItemDependency, ?complete_change_set: Coordinator::Write::Operations::ExecuteCompleteChangeSet, ?schema_registry: Coordinator::Write::EventSchemaRegistry, ?stream_factory: Coordinator::Write::StreamFactory) -> void
    def call: (PgEventstore::Event event) -> nil
  end
end
