module Coordinator
  module Processes
    module ProcessManagers
      class CoordinationTaskExecutor
        def initialize: (event_store: Write::_EventStore, ?source_builder: CoordinationTaskSourceBuilder, ?task_loader: Write::Tasks::Loader, ?transition: Write::Operations::ApplyCoordinationTaskTransition, ?start_task: Write::Operations::StartCoordinationTask, ?record_outcome: Write::Operations::RecordCoordinationTaskOutcome, ?target_command_builder: Write::Tasks::TargetCommandBuilder, ?target_executor: Write::Tasks::TargetExecutor, ?target_completion_loader: Write::Tasks::TargetCompletionLoader, ?tool_result_mapper: Write::Tasks::ToolResultMapper) -> void
        def call: (PgEventstore::Event event) -> nil
      end
    end
  end
end
