module Coordinator
  module Processes
    module ProcessManagers
      class HistoryMigration
        ACTOR: Write::Commands::Actor
        RULE_VERSION: String
        HANDLED_CODES: Array[Symbol]

        def initialize: (source_builder: HistoryMigrations::SourceBuilder, migration_loader: Write::HistoryMigrations::MigrationLoader, page_loader: Write::HistoryMigrations::PageLoader, page_locator: Write::HistoryMigrations::PageLocator, source_reader: Write::HistoryMigrations::SourceReader, page_planning_dispatcher: Write::HistoryMigrations::PagePlanningDispatcher, page_dispatcher: Write::HistoryMigrations::PageDispatcher, create_page: Write::Operations::ExecuteCreateHistoryMigrationPage, plan_page: Write::Operations::ExecutePlanHistoryMigrationPage, apply_page: Write::Operations::ExecuteApplyHistoryMigrationPage, advance_migration: Write::Operations::ExecuteAdvanceHistoryMigration, advance_application: Write::Operations::ExecuteAdvanceHistoryMigrationApplication, complete_plan: Write::Operations::ExecuteCompleteHistoryMigrationPlan, complete_migration: Write::Operations::ExecuteCompleteHistoryMigration, process_step_planner: ProcessStepPlanner) -> void
        def call: (PgEventstore::Event event) -> nil
      end
    end
  end
end
