module Coordinator
  module Shared
    module Types
      IDENTIFIER_PATTERN: Regexp
      PUBLIC_COMMAND_ID_PATTERN: Regexp
      INTERNAL_COMMAND_ID_PATTERN: Regexp
      REPOSITORY_ID_PATTERN: Regexp
      GIT_OID_PATTERN: Regexp
      SHA256_DIGEST_PATTERN: Regexp
      TIMESTAMP_PATTERN: Regexp
      UUID_V7_PATTERN: Regexp
      RESOURCE_PATH_PATTERN: Regexp
      CANDIDATE_IMPACT_KEY_PATTERN: Regexp
      MARKER_PURPOSE_PATTERN: Regexp
      MARKER_COMPONENT_PATTERN: Regexp
      SKILL_ID_PATTERN: Regexp
      SKILL_MEDIA_TYPE_PATTERN: Regexp
      DEVELOPMENT_ARTIFACT_ID_PATTERN: Regexp
      DEVELOPMENT_ARTIFACT_OBSERVATION_ID_PATTERN: Regexp
      DEVELOPMENT_ARTIFACT_RELATION_ID_PATTERN: Regexp

      RESOURCE_MARKER_MAXIMUM_BYTES: Integer
      CONTENT_MAXIMUM_BYTES: Integer
      CONTENT_BASE64_MAXIMUM_BYTES: Integer

      SKILL_NAME_MAXIMUM_BYTES: Integer
      SKILL_SCOPE_MAXIMUM_BYTES: Integer
      SKILL_DESCRIPTION_MAXIMUM_BYTES: Integer
      SKILL_INSTRUCTIONS_MAXIMUM_BYTES: Integer
      SKILL_ASSET_MAXIMUM_COUNT: Integer
      SKILL_ASSET_PATH_MAXIMUM_BYTES: Integer
      SKILL_ASSET_MAXIMUM_BYTES: Integer
      SKILL_ASSETS_TOTAL_MAXIMUM_BYTES: Integer
      SKILL_ASSET_BASE64_MAXIMUM_BYTES: Integer
      DEVELOPMENT_ARTIFACT_SCOPE_MAXIMUM_BYTES: Integer
      DEVELOPMENT_ARTIFACT_TITLE_MAXIMUM_BYTES: Integer
      DEVELOPMENT_ARTIFACT_LABEL_MAXIMUM_BYTES: Integer
      DEVELOPMENT_ARTIFACT_LABEL_MAXIMUM_COUNT: Integer
      DEVELOPMENT_ARTIFACT_SOURCE_LOCATOR_MAXIMUM_BYTES: Integer
      DEVELOPMENT_ARTIFACT_SOURCE_REVISION_MAXIMUM_BYTES: Integer
      DEVELOPMENT_ARTIFACT_COLLECTOR_MAXIMUM_BYTES: Integer
      DEVELOPMENT_ARTIFACT_CONTENT_MAXIMUM_BYTES: Integer
      DEVELOPMENT_ARTIFACT_CONTENT_BASE64_MAXIMUM_BYTES: Integer
      DEVELOPMENT_ARTIFACT_CLASSIFICATION_MAXIMUM_REVISIONS: Integer
      DEVELOPMENT_ARTIFACT_ACTIVE_RELATION_MAXIMUM_COUNT: Integer
      DEVELOPMENT_ARTIFACT_RELATION_LIFETIME_MAXIMUM_COUNT: Integer
      DEVELOPMENT_ARTIFACT_RELATION_PATH_MAXIMUM_BYTES: Integer
      DEVELOPMENT_ARTIFACT_RELATION_FRAGMENT_MAXIMUM_BYTES: Integer
      DEVELOPMENT_ARTIFACT_RELATION_SUPERSESSION_REASON_MAXIMUM_BYTES: Integer
      DEVELOPMENT_ARTIFACT_HISTORY_MAXIMUM_COUNT: Integer
      DEVELOPMENT_ARTIFACT_TARGET_ID_MAXIMUM_BYTES: Integer
      DEVELOPMENT_ARTIFACT_TARGET_NAME_MAXIMUM_BYTES: Integer
      DEVELOPMENT_ARTIFACT_TARGET_SCOPE_MAXIMUM_BYTES: Integer
      DEVELOPMENT_ARTIFACT_QUERY_MAXIMUM_ITEMS: Integer
      COORDINATION_DISCOVERY_MAXIMUM_ITEMS: Integer
      DECISION_DISCOVERY_MAXIMUM_ITEMS: Integer
      OPERATION_BATCH_MAXIMUM_ITEMS: Integer
      OPERATION_BATCH_PAGE_SIZE: Integer
      OPERATION_BATCH_QUERY_MAXIMUM_ITEMS: Integer
      OPERATION_BATCH_MAXIMUM_ENCODED_BYTES: Integer
      OPERATION_BATCH_MAXIMUM_HISTORY_EVENTS: Integer
      WRITE_SET_RESOURCE_MAXIMUM_COUNT: Integer
      CANDIDATE_MANIFEST_MAXIMUM_FILE_COUNT: Integer
      CANDIDATE_ACTUAL_RESOURCE_MAXIMUM_COUNT: Integer

      ACTOR_KINDS: Array[String]
      DEPENDENCY_KINDS: Array[String]
      OUTPUT_REQUIRED_DEPENDENCY_KINDS: Array[String]
      WORK_ITEM_OUTPUT_KINDS: Array[String]
      DEPENDENCY_REQUIRED_OUTPUT_KINDS: Array[String]
      WORK_ITEM_OUTPUT_MAXIMUM_COUNT: Integer
      GIT_OBJECT_FORMATS: Array[String]
      GUIDANCE_SOURCES: Array[String]
      STATEMENT_KINDS: Array[String]
      DECISION_EFFECTS: Array[String]
      DECISION_MODALITIES: Array[String]
      DECISION_VALUE_SCHEMAS: Array[String]
      INTERPRETATION_ASSESSMENT_STATUSES: Array[String]
      INTERPRETATION_ADJUDICATION_ACTIONS: Array[String]
      INTERPRETATION_CLARIFICATION_STATUSES: Array[String]
      INTERPRETATION_CLARIFICATION_ORIGINS: Array[String]
      INTERPRETATION_LIFECYCLE_STATUSES: Array[String]
      INTERPRETATION_ADJUDICATION_OUTCOMES: Array[String]
      DECISION_ACTIVATION_OUTCOMES: Array[String]
      DECISION_POLICY_STATUSES: Array[String]
      DECISION_PARTITION_ANCHOR_KINDS: Array[String]
      DECISION_CHANGE_KINDS: Array[String]
      AGENT_CHOICE_TYPES: Array[String]
      AGENT_CHOICE_ASSESSMENT_BASES: Array[String]
      AGENT_CHOICE_POLICY_EVALUATION_STATUSES: Array[String]
      AGENT_CHOICE_POLICY_EVALUATION_BASES: Array[String]
      AGENT_CHOICE_POLICY_REASON_CODES: Array[String]
      AGENT_CHOICE_OUTCOMES: Array[String]
      AGENT_CHOICE_OBSERVATION_STATUSES: Array[String]
      AGENT_CHOICE_IMPACT_POLICY_VERSIONS: Array[String]
      AGENT_CHOICE_IMPACT_SCAN_STATUSES: Array[String]
      AGENT_CHOICE_IMPACT_SCAN_SKIP_REASONS: Array[String]
      AGENT_CHOICE_IMPACT_ASSESSMENT_OUTCOMES: Array[String]
      AGENT_CHOICE_IMPACT_ASSESSMENT_REASONS: Array[String]
      AGENT_CHOICE_INVALIDATION_REASONS: Array[String]
      CANDIDATE_CHECKPOINT_KINDS: Array[String]
      CANDIDATE_MANIFEST_STATUSES: Array[String]
      CANDIDATE_GIT_FILE_MODES: Array[String]
      CANDIDATE_BUILD_INPUT_KINDS: Array[String]
      CANDIDATE_EVIDENCE_STATUSES: Array[String]
      CANDIDATE_IMPACT_SURFACE_DIRECTIONS: Array[String]
      CANDIDATE_IMPACT_QUERY_DIRECTIONS: Array[String]
      CANDIDATE_IMPACT_RELATIONSHIP_KINDS: Array[String]
      CANDIDATE_IMPACT_REASON_KINDS: Array[String]
      CANDIDATE_IMPACT_INDEX_ROLES: Array[String]
      CANDIDATE_IMPACT_INDEX_KINDS: Array[String]
      CANDIDATE_IMPACT_INDEX_BUCKETS: Array[String]
      CANDIDATE_IMPACT_POLICY_ENFORCEMENT_LEVELS: Array[String]
      CANDIDATE_IMPACT_REQUIRED_EVIDENCE_KINDS: Array[String]
      CANDIDATE_COMPATIBILITY_OBLIGATION_RULE_VERSIONS: Array[String]
      CANDIDATE_IMPACT_INDEX_POLICY_VERSIONS: Array[String]
      CANDIDATE_IMPACT_REGISTRY_SWEEP_RULE_VERSIONS: Array[String]
      CANDIDATE_IMPACT_PAIR_SCAN_RULE_VERSIONS: Array[String]
      CANDIDATE_IMPACT_SCAN_STATUSES: Array[String]
      CANDIDATE_IMPACT_REGISTRY_SWEEP_SKIP_REASONS: Array[String]
      CANDIDATE_IMPACT_PAIR_SCAN_SKIP_REASONS: Array[String]
      VERIFICATION_OBLIGATION_KINDS: Array[String]
      VERIFICATION_OBLIGATION_STATUSES: Array[String]
      VERIFICATION_OBLIGATION_CLAIM_STATES: Array[String]
      VERIFICATION_OBLIGATION_VALIDITY_SCAN_STATUSES: Array[String]
      VERIFICATION_EVIDENCE_CONCLUSIONS: Array[String]
      VERIFICATION_EVIDENCE_FINDING_SEVERITIES: Array[String]
      VERIFICATION_EVIDENCE_MAXIMUM_COUNT: Integer
      MERGE_SNAPSHOT_EVIDENCE_STATUSES: Array[String]
      MERGE_SNAPSHOT_REGISTRATION_POLICY_VERSIONS: Array[String]
      MERGE_SNAPSHOT_MAXIMUM_CANDIDATES: Integer
      MERGE_SNAPSHOT_VERIFICATION_EVIDENCE_KINDS: Array[String]
      MERGE_SNAPSHOT_VERIFICATION_POLICY_VERSIONS: Array[String]
      MERGE_SNAPSHOT_VERIFICATION_STATUSES: Array[String]
      MERGE_SNAPSHOT_VERIFICATION_MAXIMUM_COUNT: Integer
      MERGE_AUTHORIZATION_POLICY_VERSIONS: Array[String]
      MERGE_AUTHORIZATION_OUTCOMES: Array[String]
      MERGE_AUTHORIZATION_POLICY_STATUSES: Array[String]
      MERGE_AUTHORIZATION_OBLIGATION_STATUSES: Array[String]
      MERGE_AUTHORIZATION_REASON_CODES: Array[String]
      MERGE_AUTHORIZATION_MAXIMUM_OBLIGATIONS: Integer
      MERGE_AUTHORIZATION_MAXIMUM_REASONS: Integer
      RELEASE_SET_PREPARATION_POLICY_VERSIONS: Array[String]
      RELEASE_SET_MINIMUM_MEMBERS: Integer
      RELEASE_SET_MAXIMUM_MEMBERS: Integer
      RELEASE_SET_INTEGRATION_MAXIMUM_ATTEMPTS: Integer
      RELEASE_SET_VERIFICATION_MAXIMUM_ATTEMPTS: Integer
      RELEASE_SET_LIFECYCLE_MAXIMUM_EVENTS: Integer
      RELEASE_SET_INTEGRATION_POLICY_VERSIONS: Array[String]
      RELEASE_SET_VERIFICATION_POLICY_VERSIONS: Array[String]
      RELEASE_SET_ACTIVATION_POLICY_VERSIONS: Array[String]
      RELEASE_SET_COMPENSATION_RULE_VERSIONS: Array[String]
      RELEASE_SET_COMPLETION_RULE_VERSIONS: Array[String]
      RELEASE_SET_INTEGRATION_OUTCOMES: Array[String]
      RELEASE_SET_VERIFICATION_OUTCOMES: Array[String]
      RELEASE_SET_ACTIVATION_POINT_KINDS: Array[String]
      RELEASE_SET_COMPENSATION_ACTIONS: Array[String]
      RELEASE_SET_COMPENSATION_TRIGGER_KINDS: Array[String]
      RELEASE_SET_COMPLETION_OUTCOMES: Array[String]
      CANDIDATE_OBLIGATION_POLICY_STATUSES: Array[String]
      CANDIDATE_OBLIGATION_DECISION_OUTCOMES: Array[String]
      DECISION_ACTIVATION_INELIGIBILITY_REASONS: Array[String]
      DECISION_CORRECTION_INELIGIBILITY_REASONS: Array[String]
      SCOPE_PROVENANCE_KINDS: Array[String]
      SCOPE_ANCHOR_LEVELS: Array[String]
      DECISION_PHASES: Array[String]
      ENFORCEMENT_LEVELS: Array[String]
      RETROACTIVITY_KINDS: Array[String]
      VIOLATION_ACTIONS: Array[String]
      RESOLUTION_STRATEGIES: Array[String]
      MERGE_TARGET_KINDS: Array[String]
      MERGE_ACTIONS: Array[String]
      SUPPORTED_INTERPRETATION_TOPICS: Array[String]
      COORDINATION_TOOL_NAMES: Array[String]
      DEVELOPMENT_ARTIFACT_KINDS: Array[String]
      DEVELOPMENT_ARTIFACT_SOURCE_KINDS: Array[String]
      DEVELOPMENT_ARTIFACT_RELATION_KINDS: Array[String]
      DEVELOPMENT_ARTIFACT_CANONICAL_TARGET_KINDS: Array[String]
      DEVELOPMENT_ARTIFACT_TARGET_KINDS: Array[String]
      DEVELOPMENT_ARTIFACT_TARGET_STATUSES: Array[String]

      Identifier: untyped
      PublicCommandId: untyped
      InternalCommandId: untyped
      RepositoryId: untyped
      GitOid: untyped
      GitObjectFormat: untyped
      GuidanceSource: untyped
      Sha256Digest: untyped
      Timestamp: untyped
      UuidV7: untyped
      TaskId: untyped
      ResourceId: untyped
      ResourcePath: untyped
      ResourceKind: untyped
      ResourceMarker: untyped
      LeaseMode: untyped
      LeaseDurationSeconds: untyped
      WriteSetSize: untyped
      ExpandedWriteSetSize: untyped
      FencingToken: untyped
      CoordinationToolName: untyped
      SkillId: untyped
      SkillName: untyped
      SkillScope: untyped
      SkillDescription: untyped
      SkillInstructions: untyped
      SkillRevision: untyped
      SkillExpectedRevision: untyped
      SkillAssetPath: untyped
      SkillAssetMediaType: untyped
      SkillAssetContentBase64: untyped
      SkillAssetByteSize: untyped
      DevelopmentArtifactId: untyped
      DevelopmentArtifactObservationId: untyped
      DevelopmentArtifactRelationId: untyped
      DevelopmentArtifactScope: untyped
      DevelopmentArtifactTitle: untyped
      DevelopmentArtifactKind: untyped
      DevelopmentArtifactLabel: untyped
      DevelopmentArtifactLabels: untyped
      DevelopmentArtifactClassificationRevision: untyped
      DevelopmentArtifactEncoding: untyped
      DevelopmentArtifactMediaType: untyped
      DevelopmentArtifactContentBase64: untyped
      DevelopmentArtifactByteSize: untyped
      ContentEncoding: untyped
      ContentMediaType: untyped
      ContentText: untyped
      ContentBase64: untyped
      ContentByteSize: untyped
      DevelopmentArtifactSourceKind: untyped
      DevelopmentArtifactSourceLocator: untyped
      DevelopmentArtifactSourceRevision: untyped
      DevelopmentArtifactCollector: untyped
      DevelopmentArtifactRelationKind: untyped
      DevelopmentArtifactTargetKind: untyped
      DevelopmentArtifactCanonicalTargetKind: untyped
      DevelopmentArtifactTargetStatus: untyped
      DevelopmentArtifactTargetId: untyped
      DevelopmentArtifactTargetName: untyped
      DevelopmentArtifactTargetScope: untyped
      DevelopmentArtifactRelationPath: untyped
      DevelopmentArtifactRelationFragment: untyped
      DevelopmentArtifactRelationSupersessionReason: untyped
      OperationBatchId: untyped
      OperationBatchItemIndex: untyped
      OperationBatchTotal: untyped
      OperationBatchPageSize: untyped
      OperationBatchEncodedByteSize: untyped
      OperationBatchTargetTool: untyped
      OperationBatchItemStatus: untyped
      OperationBatchStatus: untyped
      Marker: untyped
      MarkerPurpose: untyped
      MarkerComponent: untyped
      MarkerComponents: untyped
      ActorKind: untyped
      DependencyKind: untyped
      WorkItemOutputKind: untyped
      DependencyRequiredOutputKind: untyped
      Goal: untyped
      GuidanceText: untyped
      Criterion: untyped
      AcceptanceCriteria: untyped
      WorkItemAcceptanceCriteria: untyped
      StateAcceptanceCriteria: untyped
      WorkItemStateAcceptanceCriteria: untyped
      WorkItemIds: untyped
      ReadinessWorkItemIds: untyped
      GuidanceRepositoryIds: untyped
      EvidencePolicyStatus: untyped
      InterpretationPolicyStatus: untyped
      StatementKind: untyped
      DecisionEffect: untyped
      DecisionModality: untyped
      DecisionValueSchema: untyped
      InterpretationAssessmentStatus: untyped
      InterpretationAdjudicationAction: untyped
      InterpretationClarificationStatus: untyped
      InterpretationClarificationOrigin: untyped
      InterpretationLifecycleStatus: untyped
      InterpretationAdjudicationOutcome: untyped
      DecisionActivationOutcome: untyped
      DecisionCorrectionOutcome: untyped
      DecisionPolicyStatus: untyped
      DecisionPartitionAnchorKind: untyped
      DecisionChangeKind: untyped
      AgentChoiceType: untyped
      AgentChoiceAssessmentBasis: untyped
      AgentChoicePolicyEvaluationStatus: untyped
      AgentChoicePolicyEvaluationBasis: untyped
      AgentChoicePolicyReasonCode: untyped
      AgentChoiceOutcome: untyped
      AgentChoiceObservationStatus: untyped
      AgentChoiceImpactPolicyVersion: untyped
      AgentChoiceImpactScanStatus: untyped
      AgentChoiceImpactScanSkipReason: untyped
      AgentChoiceImpactAssessmentOutcome: untyped
      AgentChoiceImpactAssessmentReason: untyped
      AgentChoiceInvalidationReason: untyped
      CandidateCheckpointKind: untyped
      CandidateManifestStatus: untyped
      CandidateGitFileMode: untyped
      CandidateBuildInputKind: untyped
      CandidateEvidenceStatus: untyped
      CandidateImpactKey: untyped
      CandidateImpactValue: untyped
      CandidateAnalyzerVersion: untyped
      CandidateImpactQueryDirection: untyped
      CandidateImpactRelationshipKind: untyped
      CandidateImpactReasonKind: untyped
      CandidateImpactIndexRole: untyped
      CandidateImpactIndexKind: untyped
      CandidateImpactIndexBucket: untyped
      CandidateImpactPolicyEnforcementLevel: untyped
      CandidateImpactRequiredEvidenceKind: untyped
      CandidateImpactRequiredEvidenceKinds: untyped
      CandidateCompatibilityObligationRuleVersion: untyped
      CandidateImpactIndexPolicyVersion: untyped
      CandidateImpactRegistrySweepRuleVersion: untyped
      CandidateImpactPairScanRuleVersion: untyped
      CandidateImpactScanRuleVersion: untyped
      CandidateImpactScanStatus: untyped
      CandidateImpactRegistrySweepSkipReason: untyped
      CandidateImpactPairScanSkipReason: untyped
      CandidateImpactScanPageSize: untyped
      CandidateImpactScanPageRegistrationCount: untyped
      CandidateImpactPairScanMarkers: untyped
      VerificationObligationKind: untyped
      VerificationObligationStatus: untyped
      VerificationObligationClaimState: untyped
      VerificationObligationWaiverReasonCode: untyped
      VerificationObligationWaiverReasonSummary: untyped
      VerificationObligationInvalidationRuleVersion: untyped
      VerificationObligationValidityScanStatus: untyped
      VerificationObligationValidityPageSize: untyped
      VerificationObligationValidityPageCount: untyped
      VerificationEvidenceConclusion: untyped
      VerificationEvidenceFindingSeverity: untyped
      VerificationEvidenceProducerName: untyped
      VerificationEvidenceProducerVersion: untyped
      VerificationEvidenceFindingCode: untyped
      VerificationEvidenceFindingSummary: untyped
      MergeSnapshotEvidenceStatus: untyped
      MergeSnapshotRegistrationPolicyVersion: untyped
      MergeSnapshotCandidateCount: untyped
      MergeSnapshotProducerName: untyped
      MergeSnapshotProducerVersion: untyped
      MergeSnapshotVerificationEvidenceKind: untyped
      MergeSnapshotVerificationPolicyVersion: untyped
      MergeSnapshotVerificationStatus: untyped
      MergeAuthorizationPolicyVersion: untyped
      MergeAuthorizationOutcome: untyped
      MergeAuthorizationPolicyStatus: untyped
      MergeAuthorizationObligationStatus: untyped
      MergeAuthorizationReasonCode: untyped
      MergeAuthorizationRequiredEvidenceKinds: untyped
      MergeObservationPolicyVersion: untyped
      ReleaseSetPreparationPolicyVersion: untyped
      ReleaseSetMemberPosition: untyped
      ReleaseSetIntegrationPolicyVersion: untyped
      ReleaseSetVerificationPolicyVersion: untyped
      ReleaseSetIntegrationOutcome: untyped
      ReleaseSetVerificationOutcome: untyped
      ReleaseSetIntegrationAttemptNumber: untyped
      ReleaseSetVerificationAttemptNumber: untyped
      ReleaseSetFailureCode: untyped
      ReleaseSetEvidenceSummary: untyped
      ReleaseSetFindingSeverity: untyped
      CandidateObligationPolicyStatus: untyped
      CandidateObligationDecisionOutcome: untyped
      CandidateImpactReasonMatches: untyped
      CandidateEvidenceRevision: untyped
      CandidateManifestSize: untyped
      CandidateBuildInputCount: untyped
      CandidateEnvironmentCount: untyped
      CandidateCollectorVersion: untyped
      CandidateEnvironmentName: untyped
      CandidateEnvironmentValue: untyped
      CandidateTargetBranch: untyped
      GlobalPosition: untyped
      AgentChoiceImpactPageSize: untyped
      AgentChoiceImpactPageChoiceCount: untyped
      AgentChoiceImpactListLimit: untyped
      DecisionActivationIneligibilityReason: untyped
      DecisionActivationIneligibilityReasons: untyped
      DecisionCorrectionIneligibilityReason: untyped
      DecisionCorrectionIneligibilityReasons: untyped
      ScopeProvenanceKind: untyped
      ScopeAnchorLevel: untyped
      DecisionPhase: untyped
      EnforcementLevel: untyped
      RetroactivityKind: untyped
      ViolationAction: untyped
      ResolutionStrategy: untyped
      MergeTargetKind: untyped
      MergeAction: untyped
      SupportedInterpretationTopic: untyped
      ClassifierConfidenceMillionths: untyped
      SourceCharacterIndex: untyped
      InterpretationLabel: untyped
      InterpretationDescription: untyped
      InterpretationLabels: untyped
      InterpretationOptions: untyped
      DecisionIdentifiers: untyped
      ScopeIdentifiers: untyped
      ScopeRepositoryIds: untyped
      ScopePaths: untyped
      InterpretationReasons: untyped
      InterpretationPageLimit: untyped
      StreamRevisionCursor: untyped
      StreamRevision: untyped
      DecisionPartitions: untyped
    end
  end
end
