module Coordinator
  module Shared
    module Types
      IDENTIFIER_PATTERN: Regexp
      REPOSITORY_ID_PATTERN: Regexp
      GIT_OID_PATTERN: Regexp
      SHA256_DIGEST_PATTERN: Regexp
      TIMESTAMP_PATTERN: Regexp
      UUID_V7_PATTERN: Regexp
      RESOURCE_PATH_PATTERN: Regexp
      CANDIDATE_IMPACT_KEY_PATTERN: Regexp
      MARKER_PURPOSE_PATTERN: Regexp
      MARKER_COMPONENT_PATTERN: Regexp

      ACTOR_KINDS: Array[String]
      DEPENDENCY_KINDS: Array[String]
      OUTPUT_REQUIRED_DEPENDENCY_KINDS: Array[String]
      GIT_OBJECT_FORMATS: Array[String]
      GUIDANCE_SOURCES: Array[String]
      STATEMENT_KINDS: Array[String]
      DECISION_EFFECTS: Array[String]
      DECISION_MODALITIES: Array[String]
      DECISION_VALUE_SCHEMAS: Array[String]
      INTERPRETATION_ASSESSMENT_STATUSES: Array[String]
      INTERPRETATION_ADJUDICATION_ACTIONS: Array[String]
      INTERPRETATION_CLARIFICATION_STATUSES: Array[String]
      INTERPRETATION_CLARIFICATION_ORIGINS: Array[String]
      INTERPRETATION_LIFECYCLE_STATUSES: Array[String]
      INTERPRETATION_ADJUDICATION_OUTCOMES: Array[String]
      DECISION_ACTIVATION_OUTCOMES: Array[String]
      DECISION_POLICY_STATUSES: Array[String]
      DECISION_PARTITION_ANCHOR_KINDS: Array[String]
      DECISION_CHANGE_KINDS: Array[String]
      AGENT_CHOICE_TYPES: Array[String]
      AGENT_CHOICE_ASSESSMENT_BASES: Array[String]
      AGENT_CHOICE_POLICY_EVALUATION_STATUSES: Array[String]
      AGENT_CHOICE_POLICY_EVALUATION_BASES: Array[String]
      AGENT_CHOICE_POLICY_REASON_CODES: Array[String]
      AGENT_CHOICE_OUTCOMES: Array[String]
      AGENT_CHOICE_OBSERVATION_STATUSES: Array[String]
      AGENT_CHOICE_IMPACT_POLICY_VERSIONS: Array[String]
      AGENT_CHOICE_IMPACT_SCAN_STATUSES: Array[String]
      AGENT_CHOICE_IMPACT_SCAN_SKIP_REASONS: Array[String]
      AGENT_CHOICE_IMPACT_ASSESSMENT_OUTCOMES: Array[String]
      AGENT_CHOICE_IMPACT_ASSESSMENT_REASONS: Array[String]
      AGENT_CHOICE_INVALIDATION_REASONS: Array[String]
      CANDIDATE_CHECKPOINT_KINDS: Array[String]
      CANDIDATE_MANIFEST_STATUSES: Array[String]
      CANDIDATE_GIT_FILE_MODES: Array[String]
      CANDIDATE_BUILD_INPUT_KINDS: Array[String]
      CANDIDATE_EVIDENCE_STATUSES: Array[String]
      CANDIDATE_IMPACT_SURFACE_DIRECTIONS: Array[String]
      CANDIDATE_IMPACT_QUERY_DIRECTIONS: Array[String]
      DECISION_ACTIVATION_INELIGIBILITY_REASONS: Array[String]
      DECISION_CORRECTION_INELIGIBILITY_REASONS: Array[String]
      SCOPE_PROVENANCE_KINDS: Array[String]
      SCOPE_ANCHOR_LEVELS: Array[String]
      DECISION_PHASES: Array[String]
      ENFORCEMENT_LEVELS: Array[String]
      RETROACTIVITY_KINDS: Array[String]
      VIOLATION_ACTIONS: Array[String]
      RESOLUTION_STRATEGIES: Array[String]
      MERGE_TARGET_KINDS: Array[String]
      MERGE_ACTIONS: Array[String]
      SUPPORTED_INTERPRETATION_TOPICS: Array[String]
      COORDINATION_TOOL_NAMES: Array[String]

      Identifier: untyped
      RepositoryId: untyped
      GitOid: untyped
      GitObjectFormat: untyped
      GuidanceSource: untyped
      Sha256Digest: untyped
      Timestamp: untyped
      UuidV7: untyped
      TaskId: untyped
      ResourcePath: untyped
      ResourceKind: untyped
      LeaseMode: untyped
      LeaseDurationSeconds: untyped
      WriteSetSize: untyped
      ExpandedWriteSetSize: untyped
      FencingToken: untyped
      CoordinationToolName: untyped
      Marker: untyped
      MarkerPurpose: untyped
      MarkerComponent: untyped
      MarkerComponents: untyped
      ActorKind: untyped
      DependencyKind: untyped
      Goal: untyped
      GuidanceText: untyped
      Criterion: untyped
      AcceptanceCriteria: untyped
      WorkItemAcceptanceCriteria: untyped
      StateAcceptanceCriteria: untyped
      WorkItemStateAcceptanceCriteria: untyped
      WorkItemIds: untyped
      ReadinessWorkItemIds: untyped
      GuidanceRepositoryIds: untyped
      EvidencePolicyStatus: untyped
      InterpretationPolicyStatus: untyped
      StatementKind: untyped
      DecisionEffect: untyped
      DecisionModality: untyped
      DecisionValueSchema: untyped
      InterpretationAssessmentStatus: untyped
      InterpretationAdjudicationAction: untyped
      InterpretationClarificationStatus: untyped
      InterpretationClarificationOrigin: untyped
      InterpretationLifecycleStatus: untyped
      InterpretationAdjudicationOutcome: untyped
      DecisionActivationOutcome: untyped
      DecisionCorrectionOutcome: untyped
      DecisionPolicyStatus: untyped
      DecisionPartitionAnchorKind: untyped
      DecisionChangeKind: untyped
      AgentChoiceType: untyped
      AgentChoiceAssessmentBasis: untyped
      AgentChoicePolicyEvaluationStatus: untyped
      AgentChoicePolicyEvaluationBasis: untyped
      AgentChoicePolicyReasonCode: untyped
      AgentChoiceOutcome: untyped
      AgentChoiceObservationStatus: untyped
      AgentChoiceImpactPolicyVersion: untyped
      AgentChoiceImpactScanStatus: untyped
      AgentChoiceImpactScanSkipReason: untyped
      AgentChoiceImpactAssessmentOutcome: untyped
      AgentChoiceImpactAssessmentReason: untyped
      AgentChoiceInvalidationReason: untyped
      CandidateCheckpointKind: untyped
      CandidateManifestStatus: untyped
      CandidateGitFileMode: untyped
      CandidateBuildInputKind: untyped
      CandidateEvidenceStatus: untyped
      CandidateImpactKey: untyped
      CandidateImpactValue: untyped
      CandidateAnalyzerVersion: untyped
      CandidateImpactQueryDirection: untyped
      CandidateEvidenceRevision: untyped
      CandidateManifestSize: untyped
      CandidateBuildInputCount: untyped
      CandidateEnvironmentCount: untyped
      CandidateCollectorVersion: untyped
      CandidateEnvironmentName: untyped
      CandidateEnvironmentValue: untyped
      CandidateTargetBranch: untyped
      GlobalPosition: untyped
      AgentChoiceImpactPageSize: untyped
      AgentChoiceImpactPageChoiceCount: untyped
      AgentChoiceImpactListLimit: untyped
      DecisionActivationIneligibilityReason: untyped
      DecisionActivationIneligibilityReasons: untyped
      DecisionCorrectionIneligibilityReason: untyped
      DecisionCorrectionIneligibilityReasons: untyped
      ScopeProvenanceKind: untyped
      ScopeAnchorLevel: untyped
      DecisionPhase: untyped
      EnforcementLevel: untyped
      RetroactivityKind: untyped
      ViolationAction: untyped
      ResolutionStrategy: untyped
      MergeTargetKind: untyped
      MergeAction: untyped
      SupportedInterpretationTopic: untyped
      ClassifierConfidenceMillionths: untyped
      SourceCharacterIndex: untyped
      InterpretationLabel: untyped
      InterpretationDescription: untyped
      InterpretationLabels: untyped
      InterpretationOptions: untyped
      DecisionIdentifiers: untyped
      ScopeIdentifiers: untyped
      ScopeRepositoryIds: untyped
      ScopePaths: untyped
      InterpretationReasons: untyped
      InterpretationPageLimit: untyped
      StreamRevisionCursor: untyped
      StreamRevision: untyped
      DecisionPartitions: untyped
    end
  end
end
