module Coordinator
  module Mcp
    class MutationTool < Tool
      def self.operation: () -> String
                        | (String key) -> String
      def self.call: (?server_context: ::MCP::ServerContext?, **untyped arguments) -> Tasks::ResultV1::Created
    end
  end
end
