module Coordinator
  module Mcp
    class QueryTool < Tool
      def self.query: () -> String
                    | (String key) -> String
      def self.call: (?server_context: untyped, **untyped arguments) -> untyped
    end
  end
end
