module Coordinator
  module Mcp
    class ServerFactory
      CAPABILITIES: Hash[Symbol, untyped]
      INSTRUCTIONS: String

      def initialize: (tasks_extension: Tasks::Extension) -> void
      def call: () -> Tasks::Server
    end
  end
end
