module Coordinator
  module Write
    module Domain
      module CoordinationTasks
        class AcknowledgeInput
          def call: (state: State, command: Commands::AcknowledgeTaskInput) -> Dry::Monads::Result
        end
      end
    end
  end
end
