module Coordinator
  module Write
    module Domain
      module CoordinationTasks
        class Cancel
          def call: (state: State, command: Commands::CancelCoordinationTask) -> untyped
        end
      end
    end
  end
end
