module Coordinator
  module Write
    module Domain
      module CoordinationTasks
        class Submit
          def call: (state: State, command: Commands::SubmitCoordinationTask) -> Dry::Monads::Result
        end
      end
    end
  end
end
