module Coordinator
  module Processes
    module Subscriptions
      class AgentChoiceDecisionImpact < Shared::Subscriptions::Registration
        DEFINITION: ProcessDefinition

        def initialize: (handler: ProcessManagers::AgentChoiceDecisionImpact, ?pull_interval: Integer | Float) -> void
      end
    end
  end
end
