module Coordinator::Processes::Subscriptions
  class BuildProgress < Coordinator::Shared::Subscriptions::Registration
    DEFINITION: ProcessDefinition
    def initialize: (handler: Coordinator::Processes::ProcessManagers::BuildProgress, ?pull_interval: Float) -> void
  end
end
