module Coordinator
  module Processes
    module Subscriptions
      class CoordinationTaskExecutor < Shared::Subscriptions::Registration
        LANE_COUNT: Integer

        def initialize: (handler: ProcessManagers::CoordinationTaskExecutor, lane_index: Integer, ?pull_interval: Float, ?execution_lane: Write::Tasks::ExecutionLane) -> void
      end
    end
  end
end
