module Coordinator::Processes
  module Subscriptions
    class MergeSnapshotVerification < Coordinator::Shared::Subscriptions::Registration
      DEFINITION: untyped

      def initialize: (handler: untyped, ?pull_interval: ::Float) -> void
    end
  end
end
