module Coordinator
  module Processes
    module Subscriptions
      class ResourceBoundaryMaintenance < Shared::Subscriptions::Registration
        DEFINITION: Shared::Subscriptions::Definition

        def initialize: (
          handler: ProcessManagers::ResourceBoundaryMaintenance,
          ?pull_interval: Integer | Float
        ) -> void
      end
    end
  end
end
