module Coordinator
  module Processes
    module Subscriptions
      class WorkIntentionExpiryScheduler < Shared::Subscriptions::Registration
        DEFINITION: Shared::Subscriptions::Definition

        def initialize: (handler: ProcessManagers::WorkIntentionExpiryScheduler, ?pull_interval: Integer | Float) -> void
      end
    end
  end
end
