module Coordinator
  module Write
    module Interpretations
      class InterpretationProposalEvidenceV1 < Shared::Value
        def proposal: () -> Events::DecisionInterpretationProposedV1
        def event: () -> EventReference
      end
    end
  end
end
