module Coordinator::Write::Domain::MergeObservations
  class Record
    def initialize: (?stream_factory: Coordinator::Write::StreamFactory) -> void
    def call: (history: HistoryV1, command: Coordinator::Write::Commands::RecordMergeObservation) -> Dry::Monads::Result
  end
end
