module Coordinator::Write
  module CandidateObligationScans
    class StartPreparationV1 < Coordinator::Shared::Value
      def started_at: () -> String
      def event_id: () -> String
    end
  end
end
