module Coordinator
  module Write
    module Metadata
      class CommandTerminalV1 < EventMetadata
        def emitted_events: () -> Array[EventReference]
        def rejection: () -> Tasks::DomainErrorV1::domain_error?
      end
    end
  end
end
