module Coordinator
  module Write
    module Metadata
      class OperationBatchCreationV2 < EventMetadata
        def manifest_digest: () -> String
        def page_size: () -> Integer
      end
    end
  end
end
