module Coordinator
  module Write
    module Domain
      module WorkItems
        class Create
          def initialize: (?stream_factory: StreamFactory) -> void
          def call: (change_set_state: ChangeSets::State, work_item_state: State, repository_registration: RepositoryRegistrationV2?, command: Commands::CreateWorkItem, occurred_at: String) -> Dry::Monads::Result
        end
      end
    end
  end
end
