module Coordinator
  module Read
    module Subscriptions
      class CommandReceipts < Shared::Subscriptions::Registration
        DEFINITION: ReadModelDefinition

        def initialize: (handler: Projectors::CommandReceiptsV1, ?pull_interval: Integer | Float) -> void
      end
    end
  end
end
