module Coordinator
  module Read
    module Subscriptions
      class DevelopmentArtifacts < Shared::Subscriptions::Registration
        DEFINITION: ReadModelDefinition
        def initialize: (handler: Projectors::DevelopmentArtifactsV1, ?pull_interval: Integer | Float) -> void
      end
    end
  end
end
