module Coordinator::Write
  module CandidateObligations
    class Matcher
      def call: (
        source: CandidateEvidenceV1 | CandidateEvidenceV2,
        target: CandidateEvidenceV1 | CandidateEvidenceV2
      ) -> Array[ImpactReasonV1]
    end
  end
end
