module Coordinator::Write
  module CandidateObligations
    class ObligationLoader
      def initialize: (
        event_store: Coordinator::Write::_EventStore,
        ?schema_registry: Coordinator::Write::EventSchemaRegistry
      ) -> void
      def find: (NaturalKeyV1 natural_key) -> Coordinator::Write::VerificationObligations::PersistedDefinitionV2?
    end
  end
end
