module Coordinator
  module Write
    module Contracts
      class AdjudicateDecisionInterpretation < Dry::Validation::Contract
        def call: (command_input input) -> Dry::Validation::Result
      end
    end
  end
end
