module Coordinator::Write
  module Candidates
    class ImpactIndexValueDocumentV1 < Coordinator::Shared::Value
      SCHEMA: String

      def schema: () -> String
      def kind: () -> String
      def value: () -> String
    end
  end
end
