module Coordinator
  module Write
    module Candidates
      class SubmissionEvidenceV1 < Coordinator::Shared::Value
        attr_reader object_format: String
        attr_reader manifest: ChangeManifestV1
        attr_reader build_context: BuildContextV1?
        attr_reader actual_resources: Array[ActualResourceV2]
      end
    end
  end
end
