module Coordinator
  module Write
    module Domain
      module Attempts
        class Abandon
          def initialize: (?stream_factory: StreamFactory) -> void
          def call: (
            attempt_state: State,
            candidate_state: Coordinator::Write::Candidates::StateV2?,
            work_item_state: Domain::WorkItems::State,
            set_state: Domain::WorkIntentions::SetState,
            member_states: Array[Domain::WorkIntentions::State],
            command: Commands::AbandonAttempt,
            abandoned_at: String
          ) -> Dry::Monads::Result
        end
      end
    end
  end
end
