module Coordinator
  module Processes
    class ChangeSetActivationSource < Shared::Value
      def event: () -> PgEventstore::Event
      def reference: () -> Write::EventReference
      def payload: () -> Write::Events::ChangeSetActivatedV1
      def correlation_id: () -> String
    end
  end
end
