module Coordinator
  module Processes
    class CoordinationTaskSource < Shared::Value
      def event: () -> PgEventstore::Event
      def reference: () -> Write::EventReference
      def payload: () -> Write::Events::CoordinationTaskSubmittedV3
    end
  end
end
