module Coordinator
  module Processes
    class LeaseExpiryPolicy
      HANDLED_OUTCOME_CODES: Array[Symbol]

      def initialize: (
        event_store: Write::_EventStore,
        source_loader: LeaseExpirySourceLoader,
        ?command_builder: LeaseExpiryCommandBuilder,
        ?process_step_planner: ProcessStepPlanner,
        operation: Write::Operations::ExecuteExpireResourceLease
      ) -> void

      def call: (LeaseExpirySourceLocatorV1 locator) -> Dry::Monads::Result
    end
  end
end
