module Coordinator
  module Processes
    class LeaseExpirySource < Shared::Value
      type payload = Write::Events::ResourceLeaseAcquiredV1 | Write::Events::ResourceLeaseRenewedV1

      def event: () -> PgEventstore::Event
      def reference: () -> Write::EventReference
      def payload: () -> payload
    end
  end
end
