module Coordinator::Write::ChangeSetCompletions
  class SourceEvidenceV1 < Coordinator::Shared::Value
    type payload = Coordinator::Write::Events::WorkItemCompletedV1 | Coordinator::Write::Events::ReleaseSetCompletedV1

    def event: () -> PgEventstore::Event
    def reference: () -> Coordinator::Write::EventReference
    def payload: () -> payload
  end
end
