module Coordinator::Write::ChangeSetCompletions
  class WorkItemLoader
    def initialize: (event_store: Coordinator::Write::_EventStore, ?stream_factory: Coordinator::Write::StreamFactory, ?schema_registry: Coordinator::Write::EventSchemaRegistry) -> void
    def call: (Coordinator::Write::Domain::ChangeSets::State change_set_state) -> Dry::Monads::Result
  end
end
