module Coordinator
  module Write
    module Domain
      module DevelopmentArtifacts
        class Capture
          def initialize: (?stream_factory: StreamFactory) -> void
          def call: (state: State, observation_state: ObservationState, command: Commands::CaptureDevelopmentArtifact, captured_at: String) -> Dry::Monads::Result
        end
      end
    end
  end
end
