module Coordinator
  module Write
    module Domain
      module DevelopmentArtifacts
        class CorrectClassificationV2
          def initialize: (?stream_factory: StreamFactory) -> void
          def call: (state: ObservationState, command: Commands::CorrectDevelopmentArtifactClassification, ?artifact_state: State?, fact_event_references: Array[EventReference]) -> Dry::Monads::Result
        end
      end
    end
  end
end
