module Coordinator
  module Write
    module Domain
      module DevelopmentArtifacts
        class DeclareRelation
          def initialize: (?stream_factory: StreamFactory, ?relation_registry: Shared::DevelopmentArtifactRelationRegistry) -> void
          def call: (state: State, command: Commands::DeclareDevelopmentArtifactRelation, target: Write::DevelopmentArtifacts::RelationTargetV1, declared_at: String) -> Dry::Monads::Result
        end
      end
    end
  end
end
