module Coordinator
  module Write
    module Domain
      module DevelopmentArtifacts
        class State < Shared::Value
          type granular_event = Events::DevelopmentArtifactCreatedV1 | Events::DevelopmentArtifactScopeChangedV1 | Events::DevelopmentArtifactTitleChangedV1 | Events::DevelopmentArtifactKindChangedV1 | Events::DevelopmentArtifactLabelAddedV1 | Events::DevelopmentArtifactLabelRemovedV1 | Events::DevelopmentArtifactSourceChangedV1 | Events::DevelopmentArtifactContentChangedV1
          def self.initial: () -> State
          type history_event = granular_event

          def self.reduce: (Array[history_event] events, ?metadata_by_event: Hash[Integer, Hash[String, untyped]]) -> State
          def created: () -> Events::DevelopmentArtifactCreatedV1?
          def scope: () -> Events::DevelopmentArtifactScopeChangedV1?
          def title: () -> Events::DevelopmentArtifactTitleChangedV1?
          def kind: () -> Events::DevelopmentArtifactKindChangedV1?
          def labels: () -> Array[String]
          def source: () -> Events::DevelopmentArtifactSourceChangedV1?
          def content: () -> Events::DevelopmentArtifactContentChangedV1?
          def content_metadata: () -> Write::DevelopmentArtifacts::ContentDescriptorV1?
          def source_collector: () -> String?
        end
      end
    end
  end
end
