module Coordinator
  module Read
    module Projectors
      class DecisionInterpretationsV1
        PROJECTION: ProjectionDefinition

        def initialize: (
          ?contract: Contracts::DecisionInterpretationSourceEvent,
          source_loader: Interpretations::ProjectionSourceLoader,
          ?schema_registry: Write::EventSchemaRegistry,
          ?interpretations: Repositories::DecisionInterpretations,
          ?processed_events: Repositories::ProcessedProjectionEvents
        ) -> void
        def call: (PgEventstore::Event event) -> void
      end
    end
  end
end
