module Coordinator
  module Read
    module Projectors
      class DevelopmentArtifactsV1
        PROJECTION: ProjectionDefinition
        def initialize: (?contract: Contracts::DevelopmentArtifactSourceEvent, ?schema_registry: Write::EventSchemaRegistry, event_store: Write::_EventStore, ?artifacts: Repositories::DevelopmentArtifacts, ?processed_events: Repositories::ProcessedProjectionEvents) -> void
        def call: (PgEventstore::Event event) -> void
      end
    end
  end
end
