module Coordinator::Read::Projectors
  class ReleaseSetsV1
    PROJECTION: Coordinator::Read::ProjectionDefinition

    def initialize: (?contract: Coordinator::Read::Contracts::ReleaseSetSourceEvent, ?schema_registry: Coordinator::Write::EventSchemaRegistry, ?release_sets: Coordinator::Read::Repositories::ReleaseSets, ?processed_events: Coordinator::Read::Repositories::ProcessedProjectionEvents) -> void
    def call: (PgEventstore::Event event) -> nil

    private

    def load_payload: (PgEventstore::Event event) -> Coordinator::Write::Events::ReleaseSetPreparedV1
  end
end
