module Coordinator
  module Read
    module Projectors
      class ResourcesV1
        PROJECTION: ProjectionDefinition

        def initialize: (?contract: Contracts::ResourceSourceEvent, ?schema_registry: Write::EventSchemaRegistry, ?resources: Repositories::Resources, ?processed_events: Repositories::ProcessedProjectionEvents) -> void
        def call: (PgEventstore::Event event) -> void
      end
    end
  end
end
