module Coordinator
  module Read
    module Projectors
      class SkillsV1
        PROJECTION: ProjectionDefinition

        def initialize: (projection_builder: Write::Skills::PublicationProjectionBuilderV3, ?contract: Contracts::SkillSourceEvent, ?skills: Repositories::Skills, ?processed_events: Repositories::ProcessedProjectionEvents) -> void
        def call: (PgEventstore::Event event) -> void
      end
    end
  end
end
