module Coordinator
  module Read
    module Projectors
      class UserUtterancesV1
        PROJECTION: ProjectionDefinition

        def initialize: (
          ?contract: Contracts::GuidanceSourceEvent,
          ?schema_registry: Write::EventSchemaRegistry,
          ?utterances: Repositories::UserUtterances,
          ?processed_events: Repositories::ProcessedProjectionEvents
        ) -> void
        def call: (PgEventstore::Event event) -> void
      end
    end
  end
end
