module Coordinator
  module Read
    module Queries
      class CandidateImpactGet
        def initialize: (
          ?contract: Contracts::CandidateImpactGet,
          ?impacts: Repositories::CandidateImpacts
        ) -> void
        %a{rbs:test:skip}
        def call: (command_input input) -> QueryResultV1
      end
    end
  end
end
