module Coordinator
  module Read
    module Queries
      class CandidateGet
        def initialize: (?contract: Contracts::CandidateGet, ?candidates: Repositories::Candidates) -> void
        %a{rbs:test:skip}
        def call: (command_input input) -> QueryResultV1
      end
    end
  end
end
