module Coordinator
  module Read
    module Queries
      class DecisionInterpretationList
        def initialize: (
          ?contract: Contracts::DecisionInterpretationList,
          ?interpretations: Repositories::DecisionInterpretations
        ) -> void
        %a{rbs:test:skip}
        def call: (command_input input) -> QueryResultV1
      end
    end
  end
end
