module Coordinator
  module Read
    module Queries
      class DevelopmentArtifactGet
        def initialize: (?contract: Contracts::DevelopmentArtifactGet, ?artifacts: Repositories::DevelopmentArtifacts) -> void
        %a{rbs:test:skip}
        def call: (command_input input) -> QueryResultV1
      end
    end
  end
end
