module Coordinator
  module Read
    module Queries
      class GuidanceGet
        def initialize: (?contract: Contracts::GuidanceGet, ?utterances: Repositories::UserUtterances) -> void
        %a{rbs:test:skip}
        def call: (command_input input) -> QueryResultV1
      end
    end
  end
end
