module Coordinator
  module Read
    module Queries
      class ResourceGet
        def initialize: (?contract: Contracts::ResourceGet, ?resources: Repositories::Resources) -> void
        %a{rbs:test:skip}
        def call: (command_input input) -> QueryResultV1
      end
    end
  end
end
