module Coordinator
  module Write
    class DevelopmentArtifactRelationPreparationV1 < Shared::Value
      def declared_at: () -> String
      def input_digest: () -> String
      def domain_event_ids: () -> Array[String]
    end
  end
end
