module Coordinator
  module Write
    class EventReference < Shared::Value
      def event_id: () -> String
      def type: () -> String
      def stream_context: () -> String
      def stream_name: () -> String
      def stream_id: () -> String
      def stream_revision: () -> Integer
    end
  end
end
