module Coordinator
  module Write
    class EventFactory
      def initialize: (?registry: EventSchemaRegistry) -> void
      def build!: (event: Events::Base, event_id: String, metadata: EventMetadata | ProcessSteps::MetadataV1 | ProcessSteps::DispatchFailureMetadataV1, markers: Array[String], ?caused_by: PgEventstore::Event?, ?correlation_id: String?) -> PgEventstore::Event
    end
  end
end
