module Coordinator
  module Write
    class GlobalMarkedEventReadCriteria < Shared::Value
      def stream_context: () -> String
      def stream_name: () -> String
      def event_types: () -> Array[String]
      def markers: () -> Array[String]
      def maximum_count: () -> Integer
      def direction: () -> Symbol
      def from_position: () -> Integer?
      def to_position: () -> Integer?
      def query_max_count: () -> Integer
    end
  end
end
