module Coordinator
  module Write
    class GlobalMarkedEventPageCriteria < Shared::Value
      def stream_context: () -> String
      def stream_name: () -> String
      def event_type: () -> String
      def markers: () -> Array[String]
      def from_position: () -> Integer
      def to_position: () -> Integer
      def page_size: () -> Integer
      def direction: () -> Symbol
      def query_max_count: () -> Integer
    end
  end
end
