module Coordinator
  module Write
    class PersistedLeaseSetRelease < Shared::Value
      def release: () -> Events::WriteSetReleasedV2
      def events: () -> Array[PgEventstore::Event]
    end
  end
end
