module Coordinator
  module Write
    class PersistedLeaseSetReleaseV1 < Shared::Value
      def release: () -> Events::WriteSetReleasedV1
      def events: () -> Array[PgEventstore::Event]
    end
  end
end
