module Coordinator
  module Write
    class PreparedWriteSetExpansion < Shared::Value
      Resource: singleton(PreparedWorkIntentionTargetV1)

      def expanded_at: () -> String
      def input_digest: () -> String
      def resources: () -> Array[PreparedWorkIntentionTargetV1]
    end
  end
end
