module Coordinator::Write
  class PreparedChangeSetCompletionV1 < Coordinator::Shared::Value
    def occurred_at: () -> String
    def input_digest: () -> String
    def completion_event_id: () -> String
    def command_completion_event_id: () -> String
  end
end
