module Coordinator
  module Write
    class PreparedLeaseSetRenewal < Shared::Value
      def renewed_at: () -> String
      def expires_at: () -> String
      def input_digest: () -> String
      def renewals: () -> Array[PreparedLeaseRenewalV1]
      def write_set_event_id: () -> String
    end
  end
end
