module Coordinator::Write
  class ReleaseSetLifecyclePreparationV1 < Coordinator::Shared::Value
    def occurred_at: () -> String
    def input_digest: () -> String
    def domain_event_id: () -> String
  end
end
