module Coordinator
  module Write
    class StreamFactory
      def command: (String command_id) -> StreamReference
      def change_set: (String change_set_id) -> StreamReference
      def work_item: (String work_item_id) -> StreamReference
      def attempt: (String attempt_id) -> StreamReference
    end
  end
end
