module Coordinator
  module Write
    class VerificationObligationInvalidationInvocation < Shared::Value
      def command: () -> Commands::InvalidateVerificationObligation
      def caused_by_event: () -> PgEventstore::Event
      def caused_by_reference: () -> EventReference
    end
  end
end
