module Coordinator
  module Write
    class VerificationObligationValidityScanProgressInvocation < Shared::Value
      def command: () -> Commands::ProgressVerificationObligationValidityScan
      def checkpoint_event: () -> PgEventstore::Event
      def checkpoint_reference: () -> EventReference
      def caused_by: () -> PgEventstore::Event
    end
  end
end
