module Coordinator
  module Write
    module DevelopmentArtifacts
      class ContentDescriptorV1 < Shared::Value
        def encoding: () -> String
        def media_type: () -> String
        def byte_size: () -> Integer
        def content_sha256: () -> String
      end
    end
  end
end
