module Coordinator
  module Write
    module DevelopmentArtifacts
      class IdentityBuilder
        def initialize: (?canonical_json: Shared::CanonicalJson) -> void
        def call: (content: Content::TextV1 | Content::BinaryV1) -> String
      end
    end
  end
end
