module Coordinator
  module Write
    module DevelopmentArtifacts
      class RelationIdentityBuilder
        def initialize: (?id_generator: Shared::IdGenerator) -> void
        def call: () -> String
      end
    end
  end
end
