module Coordinator
  module Write
    module DevelopmentArtifacts
      class RelationAttributesV1 < Shared::Value
        def path: () -> String?
        def fragment: () -> String?
        def normalized_locator: () -> String?
      end
    end
  end
end
