module Coordinator
  module Write
    module DevelopmentArtifacts
      class UpdateChangesV1 < Shared::Value
        def scope: () -> String?
        def title: () -> String?
        def kind: () -> String?
        def labels: () -> Array[String]?
        def content: () -> (Content::TextV1 | Content::BinaryV1)?
        def source: () -> SourceV1?
      end
    end
  end
end
