module Coordinator
  module Write
    module Domain
      module VerificationObligationInvalidations
        class Invalidate
          def initialize: (?stream_factory: StreamFactory) -> void
          def call: (
            state: State,
            command: Commands::InvalidateVerificationObligation,
            superseding_partition: Coordinator::Write::CandidateObligations::PersistedEventV1
          ) -> Dry::Monads::Result
        end
      end
    end
  end
end
