module Coordinator
  module Write
    module Domain
      module HistoryMigrations
        class Advance
          include Dry::Monads::Result::Mixin

          def initialize: (?stream_factory: StreamFactory) -> void
          def call: (snapshot: Write::HistoryMigrations::MigrationSnapshotV1, page: Domain::HistoryMigrationPages::State, command: Commands::AdvanceHistoryMigration) -> Dry::Monads::Result
        end
      end
    end
  end
end
