module Coordinator
  module Write
    module Domain
      module HistoryMigrations
        class Complete
          include Dry::Monads::Result::Mixin

          def initialize: (?stream_factory: StreamFactory) -> void
          def call: (snapshot: Write::HistoryMigrations::MigrationSnapshotV1, command: Commands::CompleteHistoryMigration) -> Dry::Monads::Result
        end
      end
    end
  end
end
