module Coordinator
  module Write
    module Domain
      module HistoryMigrations
        class Start
          def initialize: (?stream_factory: StreamFactory) -> void
          def call: (state: State, command: Commands::StartHistoryMigration) -> Dry::Monads::Result
        end
      end
    end
  end
end
