module Coordinator
  module Write
    module Domain
      module HistoryMigrations
        class State < Shared::Value
          EVENT_CLASSES: Array[Class]

          def self.initial: () -> State
          def self.reduce: (Array[Events::Base] events) -> State
          def step: () -> Integer
          def migration_id: () -> String?
          def source_config_name: () -> String?
          def target_config_name: () -> String?
          def source_upper_position: () -> Integer?
          def page_size: () -> Integer?
          def absent?: () -> bool
          def started?: () -> bool
          def matches?: (Commands::StartHistoryMigration command) -> bool
          def apply: (Events::Base event) -> State
        end
      end
    end
  end
end
