module Coordinator
  module Write
    module Tasks
      class Loader
        def initialize: (event_store: _EventStore, ?stream_factory: StreamFactory, ?schema_registry: EventSchemaRegistry) -> void
        def call: (String task_id) -> Snapshot
      end
    end
  end
end
