module Coordinator
  module Write
    module Tasks
      module OutcomeV1
        type value = Completed | Failed

        class Completed < Shared::Value
          def result: () -> ToolResultV1
        end

        class Failed < Shared::Value
          def error: () -> JsonRpcErrorV1
        end
      end
    end
  end
end
