module Coordinator
  module Write
    module Tasks
      class Snapshot < Shared::Value
        def state: () -> Domain::CoordinationTasks::State
        def latest_revision: () -> Integer?
        def persisted_events: () -> Array[PgEventstore::Event]
      end
    end
  end
end
